# Docker环境配置
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://host.docker.internal:5432/group}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:host.docker.internal}
      port: ${SPRING_DATA_REDIS_PORT:6379}
