package com.github.im.server.schema.migration;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import org.postgresql.ds.PGSimpleDataSource;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import javax.sql.DataSource;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.stream.StreamSupport;

import static org.junit.jupiter.api.Assertions.*;

@Testcontainers
class TenantSchemaInventorySqlIntegrationTest {

    @Container
    static final PostgreSQLContainer<?> POSTGRES = new PostgreSQLContainer<>("postgres:16-alpine");

    private final ObjectMapper objectMapper = new ObjectMapper();

    @Test
    void inventoryCapturesDatabaseObjectsAndExcludesMigrationRuntimeTables() throws Exception {
        DataSource dataSource = dataSource();
        createRepresentativeTenantSchema(dataSource);

        String inventorySql = Files.readString(resolveInventorySql(), StandardCharsets.UTF_8);
        JsonNode inventory;
        try (Connection connection = dataSource.getConnection(); Statement statement = connection.createStatement()) {
            statement.execute("SET search_path TO trusted_tenant, public");
            try (ResultSet resultSet = statement.executeQuery(inventorySql)) {
                assertTrue(resultSet.next());
                inventory = objectMapper.readTree(resultSet.getString(1));
            }
        }

        assertEquals(1, inventory.path("format_version").asInt());
        assertEquals("trusted_tenant", inventory.path("schema").asText());

        assertTrue(hasValue(inventory.path("tables"), "table_name", "parent_item"));
        assertTrue(hasValue(inventory.path("tables"), "table_name", "child_item"));
        assertFalse(hasValue(inventory.path("tables"), "table_name", "flyway_schema_history"));
        assertFalse(hasValue(inventory.path("tables"), "table_name", "tenant_schema_metadata"));

        assertTrue(hasValue(inventory.path("columns"), "column_name", "created_at"));
        assertTrue(hasTextContaining(inventory.path("columns"), "default_expression", "now"));

        assertTrue(hasValue(inventory.path("constraints"), "constraint_type", "PRIMARY_KEY"));
        assertTrue(hasValue(inventory.path("constraints"), "constraint_type", "UNIQUE"));
        assertTrue(hasValue(inventory.path("constraints"), "constraint_type", "FOREIGN_KEY"));
        assertTrue(hasValue(inventory.path("constraints"), "constraint_type", "CHECK"));

        assertTrue(hasValue(inventory.path("indexes"), "index_name", "idx_child_item_parent"));
        assertTrue(hasValue(inventory.path("views"), "view_name", "open_parent_items"));
        assertTrue(hasValue(inventory.path("sequences"), "sequence_name", "external_sequence"));
        assertTrue(hasValue(inventory.path("triggers"), "trigger_name", "trg_child_item_touch"));
        assertTrue(hasValue(inventory.path("routines"), "routine_name", "touch_child_item"));
        assertTrue(hasTextContaining(inventory.path("routines"), "definition", "CREATE OR REPLACE FUNCTION"));
        assertTrue(hasValue(inventory.path("domains"), "domain_name", "positive_int"));
        assertTrue(hasValue(inventory.path("enum_labels"), "type_name", "task_state"));
        assertTrue(hasValue(inventory.path("enum_labels"), "label", "OPEN"));
        assertTrue(hasValue(inventory.path("enum_labels"), "label", "DONE"));
    }

    private DataSource dataSource() {
        PGSimpleDataSource dataSource = new PGSimpleDataSource();
        dataSource.setURL(POSTGRES.getJdbcUrl());
        dataSource.setUser(POSTGRES.getUsername());
        dataSource.setPassword(POSTGRES.getPassword());
        return dataSource;
    }

    private void createRepresentativeTenantSchema(DataSource dataSource) throws Exception {
        try (Connection connection = dataSource.getConnection(); Statement statement = connection.createStatement()) {
            statement.execute("CREATE SCHEMA trusted_tenant");
            statement.execute("CREATE TYPE trusted_tenant.task_state AS ENUM ('OPEN', 'DONE')");
            statement.execute("CREATE DOMAIN trusted_tenant.positive_int AS integer CHECK (VALUE > 0)");
            statement.execute("CREATE SEQUENCE trusted_tenant.external_sequence START WITH 10 INCREMENT BY 5");
            statement.execute("""
                    CREATE TABLE trusted_tenant.parent_item (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        code VARCHAR(64) NOT NULL UNIQUE,
                        state trusted_tenant.task_state NOT NULL DEFAULT 'OPEN',
                        weight trusted_tenant.positive_int NOT NULL DEFAULT 1,
                        CONSTRAINT ck_parent_item_code_length CHECK (char_length(code) > 1)
                    )
                    """);
            statement.execute("""
                    CREATE TABLE trusted_tenant.child_item (
                        id BIGINT PRIMARY KEY,
                        parent_id BIGINT NOT NULL REFERENCES trusted_tenant.parent_item(id),
                        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                    )
                    """);
            statement.execute("CREATE INDEX idx_child_item_parent ON trusted_tenant.child_item(parent_id)");
            statement.execute("""
                    CREATE VIEW trusted_tenant.open_parent_items AS
                    SELECT id, code
                    FROM trusted_tenant.parent_item
                    WHERE state = 'OPEN'
                    """);
            statement.execute("""
                    CREATE FUNCTION trusted_tenant.touch_child_item()
                    RETURNS trigger
                    LANGUAGE plpgsql
                    AS $$
                    BEGIN
                        NEW.created_at := COALESCE(NEW.created_at, NOW());
                        RETURN NEW;
                    END;
                    $$
                    """);
            statement.execute("""
                    CREATE TRIGGER trg_child_item_touch
                    BEFORE INSERT OR UPDATE ON trusted_tenant.child_item
                    FOR EACH ROW EXECUTE FUNCTION trusted_tenant.touch_child_item()
                    """);
            statement.execute("CREATE TABLE trusted_tenant.flyway_schema_history(installed_rank INT PRIMARY KEY)");
            statement.execute("CREATE TABLE trusted_tenant.tenant_schema_metadata(metadata_key VARCHAR(100) PRIMARY KEY)");
        }
    }

    private Path resolveInventorySql() {
        Path fromRepositoryRoot = Path.of("scripts", "tenant-schema-snapshot", "tenant_schema_inventory.sql");
        if (Files.isRegularFile(fromRepositoryRoot)) {
            return fromRepositoryRoot;
        }
        Path fromServerModule = Path.of("..", "scripts", "tenant-schema-snapshot", "tenant_schema_inventory.sql");
        if (Files.isRegularFile(fromServerModule)) {
            return fromServerModule;
        }
        throw new AssertionError("tenant_schema_inventory.sql not found from repository or server module working directory");
    }

    private boolean hasValue(JsonNode array, String field, String expected) {
        return StreamSupport.stream(array.spliterator(), false)
                .anyMatch(node -> expected.equals(node.path(field).asText()));
    }

    private boolean hasTextContaining(JsonNode array, String field, String expectedFragment) {
        return StreamSupport.stream(array.spliterator(), false)
                .map(node -> node.path(field).asText(""))
                .anyMatch(value -> value.contains(expectedFragment));
    }
}
