// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Account.proto

package com.github.im.common.connect.model.proto;

public final class Account {
  private Account() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code com.github.im.common.connect.model.proto.PlatformType}
   */
  public enum PlatformType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>WEB = 0;</code>
     */
    WEB(0),
    /**
     * <code>ANDROID = 1;</code>
     */
    ANDROID(1),
    /**
     * <code>IOS = 2;</code>
     */
    IOS(2),
    /**
     * <code>WINDOWS = 3;</code>
     */
    WINDOWS(3),
    /**
     * <code>MAC = 4;</code>
     */
    MAC(4),
    /**
     * <code>LINUX = 5;</code>
     */
    LINUX(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>WEB = 0;</code>
     */
    public static final int WEB_VALUE = 0;
    /**
     * <code>ANDROID = 1;</code>
     */
    public static final int ANDROID_VALUE = 1;
    /**
     * <code>IOS = 2;</code>
     */
    public static final int IOS_VALUE = 2;
    /**
     * <code>WINDOWS = 3;</code>
     */
    public static final int WINDOWS_VALUE = 3;
    /**
     * <code>MAC = 4;</code>
     */
    public static final int MAC_VALUE = 4;
    /**
     * <code>LINUX = 5;</code>
     */
    public static final int LINUX_VALUE = 5;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PlatformType valueOf(int value) {
      return forNumber(value);
    }

    public static PlatformType forNumber(int value) {
      switch (value) {
        case 0: return WEB;
        case 1: return ANDROID;
        case 2: return IOS;
        case 3: return WINDOWS;
        case 4: return MAC;
        case 5: return LINUX;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PlatformType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PlatformType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PlatformType>() {
            @java.lang.Override
            public PlatformType findValueByNumber(int number) {
              return PlatformType.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return PlatformTypeVerifier.INSTANCE;
    }

    private static final class PlatformTypeVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new PlatformTypeVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return PlatformType.forNumber(number) != null;
            }
          };

    private final int value;

    private PlatformType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.github.im.common.connect.model.proto.PlatformType)
  }

  /**
   * Protobuf enum {@code com.github.im.common.connect.model.proto.AccountOperationType}
   */
  public enum AccountOperationType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>SIGNIN = 0;</code>
     */
    SIGNIN(0),
    /**
     * <code>LOGOUT = 1;</code>
     */
    LOGOUT(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SIGNIN = 0;</code>
     */
    public static final int SIGNIN_VALUE = 0;
    /**
     * <code>LOGOUT = 1;</code>
     */
    public static final int LOGOUT_VALUE = 1;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AccountOperationType valueOf(int value) {
      return forNumber(value);
    }

    public static AccountOperationType forNumber(int value) {
      switch (value) {
        case 0: return SIGNIN;
        case 1: return LOGOUT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AccountOperationType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AccountOperationType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AccountOperationType>() {
            @java.lang.Override
            public AccountOperationType findValueByNumber(int number) {
              return AccountOperationType.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return AccountOperationTypeVerifier.INSTANCE;
    }

    private static final class AccountOperationTypeVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new AccountOperationTypeVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return AccountOperationType.forNumber(number) != null;
            }
          };

    private final int value;

    private AccountOperationType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.github.im.common.connect.model.proto.AccountOperationType)
  }

  public interface AccountInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.im.common.connect.model.proto.AccountInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     **
     *{&#64;link UserInfo#getUsername}
     * </pre>
     *
     * <code>string account = 1;</code>
     * @return The account.
     */
    java.lang.String getAccount();
    /**
     * <pre>
     **
     *{&#64;link UserInfo#getUsername}
     * </pre>
     *
     * <code>string account = 1;</code>
     * @return The bytes for account.
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    /**
     * <code>string accountName = 2;</code>
     * @return The accountName.
     */
    java.lang.String getAccountName();
    /**
     * <code>string accountName = 2;</code>
     * @return The bytes for accountName.
     */
    com.google.protobuf.ByteString
        getAccountNameBytes();

    /**
     * <code>int64 userId = 3;</code>
     * @return The userId.
     */
    long getUserId();

    /**
     * <code>string eMail = 4;</code>
     * @return The eMail.
     */
    java.lang.String getEMail();
    /**
     * <code>string eMail = 4;</code>
     * @return The bytes for eMail.
     */
    com.google.protobuf.ByteString
        getEMailBytes();

    /**
     * <code>.com.github.im.common.connect.model.proto.PlatformType platformType = 5;</code>
     * @return The enum numeric value on the wire for platformType.
     */
    int getPlatformTypeValue();
    /**
     * <code>.com.github.im.common.connect.model.proto.PlatformType platformType = 5;</code>
     * @return The platformType.
     */
    com.github.im.common.connect.model.proto.Account.PlatformType getPlatformType();
  }
  /**
   * Protobuf type {@code com.github.im.common.connect.model.proto.AccountInfo}
   */
  public  static final class AccountInfo extends
      com.google.protobuf.GeneratedMessageLite<
          AccountInfo, AccountInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:com.github.im.common.connect.model.proto.AccountInfo)
      AccountInfoOrBuilder {
    private AccountInfo() {
      account_ = "";
      accountName_ = "";
      eMail_ = "";
    }
    public static final int ACCOUNT_FIELD_NUMBER = 1;
    private java.lang.String account_;
    /**
     * <pre>
     **
     *{&#64;link UserInfo#getUsername}
     * </pre>
     *
     * <code>string account = 1;</code>
     * @return The account.
     */
    @java.lang.Override
    public java.lang.String getAccount() {
      return account_;
    }
    /**
     * <pre>
     **
     *{&#64;link UserInfo#getUsername}
     * </pre>
     *
     * <code>string account = 1;</code>
     * @return The bytes for account.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccountBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(account_);
    }
    /**
     * <pre>
     **
     *{&#64;link UserInfo#getUsername}
     * </pre>
     *
     * <code>string account = 1;</code>
     * @param value The account to set.
     */
    private void setAccount(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      account_ = value;
    }
    /**
     * <pre>
     **
     *{&#64;link UserInfo#getUsername}
     * </pre>
     *
     * <code>string account = 1;</code>
     */
    private void clearAccount() {
      
      account_ = getDefaultInstance().getAccount();
    }
    /**
     * <pre>
     **
     *{&#64;link UserInfo#getUsername}
     * </pre>
     *
     * <code>string account = 1;</code>
     * @param value The bytes for account to set.
     */
    private void setAccountBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      account_ = value.toStringUtf8();
      
    }

    public static final int ACCOUNTNAME_FIELD_NUMBER = 2;
    private java.lang.String accountName_;
    /**
     * <code>string accountName = 2;</code>
     * @return The accountName.
     */
    @java.lang.Override
    public java.lang.String getAccountName() {
      return accountName_;
    }
    /**
     * <code>string accountName = 2;</code>
     * @return The bytes for accountName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccountNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(accountName_);
    }
    /**
     * <code>string accountName = 2;</code>
     * @param value The accountName to set.
     */
    private void setAccountName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      accountName_ = value;
    }
    /**
     * <code>string accountName = 2;</code>
     */
    private void clearAccountName() {
      
      accountName_ = getDefaultInstance().getAccountName();
    }
    /**
     * <code>string accountName = 2;</code>
     * @param value The bytes for accountName to set.
     */
    private void setAccountNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      accountName_ = value.toStringUtf8();
      
    }

    public static final int USERID_FIELD_NUMBER = 3;
    private long userId_;
    /**
     * <code>int64 userId = 3;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <code>int64 userId = 3;</code>
     * @param value The userId to set.
     */
    private void setUserId(long value) {
      
      userId_ = value;
    }
    /**
     * <code>int64 userId = 3;</code>
     */
    private void clearUserId() {
      
      userId_ = 0L;
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    private java.lang.String eMail_;
    /**
     * <code>string eMail = 4;</code>
     * @return The eMail.
     */
    @java.lang.Override
    public java.lang.String getEMail() {
      return eMail_;
    }
    /**
     * <code>string eMail = 4;</code>
     * @return The bytes for eMail.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEMailBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(eMail_);
    }
    /**
     * <code>string eMail = 4;</code>
     * @param value The eMail to set.
     */
    private void setEMail(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      eMail_ = value;
    }
    /**
     * <code>string eMail = 4;</code>
     */
    private void clearEMail() {
      
      eMail_ = getDefaultInstance().getEMail();
    }
    /**
     * <code>string eMail = 4;</code>
     * @param value The bytes for eMail to set.
     */
    private void setEMailBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      eMail_ = value.toStringUtf8();
      
    }

    public static final int PLATFORMTYPE_FIELD_NUMBER = 5;
    private int platformType_;
    /**
     * <code>.com.github.im.common.connect.model.proto.PlatformType platformType = 5;</code>
     * @return The enum numeric value on the wire for platformType.
     */
    @java.lang.Override
    public int getPlatformTypeValue() {
      return platformType_;
    }
    /**
     * <code>.com.github.im.common.connect.model.proto.PlatformType platformType = 5;</code>
     * @return The platformType.
     */
    @java.lang.Override
    public com.github.im.common.connect.model.proto.Account.PlatformType getPlatformType() {
      com.github.im.common.connect.model.proto.Account.PlatformType result = com.github.im.common.connect.model.proto.Account.PlatformType.forNumber(platformType_);
      return result == null ? com.github.im.common.connect.model.proto.Account.PlatformType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.github.im.common.connect.model.proto.PlatformType platformType = 5;</code>
     * @param value The enum numeric value on the wire for platformType to set.
     */
    private void setPlatformTypeValue(int value) {
        platformType_ = value;
    }
    /**
     * <code>.com.github.im.common.connect.model.proto.PlatformType platformType = 5;</code>
     * @param value The platformType to set.
     */
    private void setPlatformType(com.github.im.common.connect.model.proto.Account.PlatformType value) {
      platformType_ = value.getNumber();
      
    }
    /**
     * <code>.com.github.im.common.connect.model.proto.PlatformType platformType = 5;</code>
     */
    private void clearPlatformType() {
      
      platformType_ = 0;
    }

    public static com.github.im.common.connect.model.proto.Account.AccountInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.im.common.connect.model.proto.Account.AccountInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.Account.AccountInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.im.common.connect.model.proto.Account.AccountInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.Account.AccountInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.im.common.connect.model.proto.Account.AccountInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.Account.AccountInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.im.common.connect.model.proto.Account.AccountInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.Account.AccountInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.github.im.common.connect.model.proto.Account.AccountInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.Account.AccountInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.im.common.connect.model.proto.Account.AccountInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.github.im.common.connect.model.proto.Account.AccountInfo prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.github.im.common.connect.model.proto.AccountInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.github.im.common.connect.model.proto.Account.AccountInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.im.common.connect.model.proto.AccountInfo)
        com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder {
      // Construct using com.github.im.common.connect.model.proto.Account.AccountInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       **
       *{&#64;link UserInfo#getUsername}
       * </pre>
       *
       * <code>string account = 1;</code>
       * @return The account.
       */
      @java.lang.Override
      public java.lang.String getAccount() {
        return instance.getAccount();
      }
      /**
       * <pre>
       **
       *{&#64;link UserInfo#getUsername}
       * </pre>
       *
       * <code>string account = 1;</code>
       * @return The bytes for account.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getAccountBytes() {
        return instance.getAccountBytes();
      }
      /**
       * <pre>
       **
       *{&#64;link UserInfo#getUsername}
       * </pre>
       *
       * <code>string account = 1;</code>
       * @param value The account to set.
       * @return This builder for chaining.
       */
      public Builder setAccount(
          java.lang.String value) {
        copyOnWrite();
        instance.setAccount(value);
        return this;
      }
      /**
       * <pre>
       **
       *{&#64;link UserInfo#getUsername}
       * </pre>
       *
       * <code>string account = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccount() {
        copyOnWrite();
        instance.clearAccount();
        return this;
      }
      /**
       * <pre>
       **
       *{&#64;link UserInfo#getUsername}
       * </pre>
       *
       * <code>string account = 1;</code>
       * @param value The bytes for account to set.
       * @return This builder for chaining.
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAccountBytes(value);
        return this;
      }

      /**
       * <code>string accountName = 2;</code>
       * @return The accountName.
       */
      @java.lang.Override
      public java.lang.String getAccountName() {
        return instance.getAccountName();
      }
      /**
       * <code>string accountName = 2;</code>
       * @return The bytes for accountName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getAccountNameBytes() {
        return instance.getAccountNameBytes();
      }
      /**
       * <code>string accountName = 2;</code>
       * @param value The accountName to set.
       * @return This builder for chaining.
       */
      public Builder setAccountName(
          java.lang.String value) {
        copyOnWrite();
        instance.setAccountName(value);
        return this;
      }
      /**
       * <code>string accountName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccountName() {
        copyOnWrite();
        instance.clearAccountName();
        return this;
      }
      /**
       * <code>string accountName = 2;</code>
       * @param value The bytes for accountName to set.
       * @return This builder for chaining.
       */
      public Builder setAccountNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAccountNameBytes(value);
        return this;
      }

      /**
       * <code>int64 userId = 3;</code>
       * @return The userId.
       */
      @java.lang.Override
      public long getUserId() {
        return instance.getUserId();
      }
      /**
       * <code>int64 userId = 3;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {
        copyOnWrite();
        instance.setUserId(value);
        return this;
      }
      /**
       * <code>int64 userId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        copyOnWrite();
        instance.clearUserId();
        return this;
      }

      /**
       * <code>string eMail = 4;</code>
       * @return The eMail.
       */
      @java.lang.Override
      public java.lang.String getEMail() {
        return instance.getEMail();
      }
      /**
       * <code>string eMail = 4;</code>
       * @return The bytes for eMail.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getEMailBytes() {
        return instance.getEMailBytes();
      }
      /**
       * <code>string eMail = 4;</code>
       * @param value The eMail to set.
       * @return This builder for chaining.
       */
      public Builder setEMail(
          java.lang.String value) {
        copyOnWrite();
        instance.setEMail(value);
        return this;
      }
      /**
       * <code>string eMail = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEMail() {
        copyOnWrite();
        instance.clearEMail();
        return this;
      }
      /**
       * <code>string eMail = 4;</code>
       * @param value The bytes for eMail to set.
       * @return This builder for chaining.
       */
      public Builder setEMailBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEMailBytes(value);
        return this;
      }

      /**
       * <code>.com.github.im.common.connect.model.proto.PlatformType platformType = 5;</code>
       * @return The enum numeric value on the wire for platformType.
       */
      @java.lang.Override
      public int getPlatformTypeValue() {
        return instance.getPlatformTypeValue();
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.PlatformType platformType = 5;</code>
       * @param value The platformType to set.
       * @return This builder for chaining.
       */
      public Builder setPlatformTypeValue(int value) {
        copyOnWrite();
        instance.setPlatformTypeValue(value);
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.PlatformType platformType = 5;</code>
       * @return The platformType.
       */
      @java.lang.Override
      public com.github.im.common.connect.model.proto.Account.PlatformType getPlatformType() {
        return instance.getPlatformType();
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.PlatformType platformType = 5;</code>
       * @param value The enum numeric value on the wire for platformType to set.
       * @return This builder for chaining.
       */
      public Builder setPlatformType(com.github.im.common.connect.model.proto.Account.PlatformType value) {
        copyOnWrite();
        instance.setPlatformType(value);
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.PlatformType platformType = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlatformType() {
        copyOnWrite();
        instance.clearPlatformType();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.github.im.common.connect.model.proto.AccountInfo)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.github.im.common.connect.model.proto.Account.AccountInfo();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "account_",
              "accountName_",
              "userId_",
              "eMail_",
              "platformType_",
            };
            java.lang.String info =
                "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "\u0003\u0002\u0004\u0208\u0005\f";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.github.im.common.connect.model.proto.Account.AccountInfo> parser = PARSER;
          if (parser == null) {
            synchronized (com.github.im.common.connect.model.proto.Account.AccountInfo.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.github.im.common.connect.model.proto.Account.AccountInfo>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.github.im.common.connect.model.proto.AccountInfo)
    private static final com.github.im.common.connect.model.proto.Account.AccountInfo DEFAULT_INSTANCE;
    static {
      AccountInfo defaultInstance = new AccountInfo();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        AccountInfo.class, defaultInstance);
    }

    public static com.github.im.common.connect.model.proto.Account.AccountInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AccountInfo> PARSER;

    public static com.google.protobuf.Parser<AccountInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
