// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OnlineUser.proto

package com.github.im.common.connect.model.proto;

public final class OnLineUser {
  private OnLineUser() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface UserSearchOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.im.common.connect.model.proto.UserSearch)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .com.github.im.common.connect.model.proto.AccountInfo accounts = 1;</code>
     */
    java.util.List<com.github.im.common.connect.model.proto.Account.AccountInfo> 
        getAccountsList();
    /**
     * <code>repeated .com.github.im.common.connect.model.proto.AccountInfo accounts = 1;</code>
     */
    com.github.im.common.connect.model.proto.Account.AccountInfo getAccounts(int index);
    /**
     * <code>repeated .com.github.im.common.connect.model.proto.AccountInfo accounts = 1;</code>
     */
    int getAccountsCount();
  }
  /**
   * Protobuf type {@code com.github.im.common.connect.model.proto.UserSearch}
   */
  public  static final class UserSearch extends
      com.google.protobuf.GeneratedMessageLite<
          UserSearch, UserSearch.Builder> implements
      // @@protoc_insertion_point(message_implements:com.github.im.common.connect.model.proto.UserSearch)
      UserSearchOrBuilder {
    private UserSearch() {
      accounts_ = emptyProtobufList();
    }
    public static final int ACCOUNTS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.github.im.common.connect.model.proto.Account.AccountInfo> accounts_;
    /**
     * <code>repeated .com.github.im.common.connect.model.proto.AccountInfo accounts = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.github.im.common.connect.model.proto.Account.AccountInfo> getAccountsList() {
      return accounts_;
    }
    /**
     * <code>repeated .com.github.im.common.connect.model.proto.AccountInfo accounts = 1;</code>
     */
    public java.util.List<? extends com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder> 
        getAccountsOrBuilderList() {
      return accounts_;
    }
    /**
     * <code>repeated .com.github.im.common.connect.model.proto.AccountInfo accounts = 1;</code>
     */
    @java.lang.Override
    public int getAccountsCount() {
      return accounts_.size();
    }
    /**
     * <code>repeated .com.github.im.common.connect.model.proto.AccountInfo accounts = 1;</code>
     */
    @java.lang.Override
    public com.github.im.common.connect.model.proto.Account.AccountInfo getAccounts(int index) {
      return accounts_.get(index);
    }
    /**
     * <code>repeated .com.github.im.common.connect.model.proto.AccountInfo accounts = 1;</code>
     */
    public com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder getAccountsOrBuilder(
        int index) {
      return accounts_.get(index);
    }
    private void ensureAccountsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.github.im.common.connect.model.proto.Account.AccountInfo> tmp = accounts_;
      if (!tmp.isModifiable()) {
        accounts_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .com.github.im.common.connect.model.proto.AccountInfo accounts = 1;</code>
     */
    private void setAccounts(
        int index, com.github.im.common.connect.model.proto.Account.AccountInfo value) {
      value.getClass();
  ensureAccountsIsMutable();
      accounts_.set(index, value);
    }
    /**
     * <code>repeated .com.github.im.common.connect.model.proto.AccountInfo accounts = 1;</code>
     */
    private void addAccounts(com.github.im.common.connect.model.proto.Account.AccountInfo value) {
      value.getClass();
  ensureAccountsIsMutable();
      accounts_.add(value);
    }
    /**
     * <code>repeated .com.github.im.common.connect.model.proto.AccountInfo accounts = 1;</code>
     */
    private void addAccounts(
        int index, com.github.im.common.connect.model.proto.Account.AccountInfo value) {
      value.getClass();
  ensureAccountsIsMutable();
      accounts_.add(index, value);
    }
    /**
     * <code>repeated .com.github.im.common.connect.model.proto.AccountInfo accounts = 1;</code>
     */
    private void addAllAccounts(
        java.lang.Iterable<? extends com.github.im.common.connect.model.proto.Account.AccountInfo> values) {
      ensureAccountsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, accounts_);
    }
    /**
     * <code>repeated .com.github.im.common.connect.model.proto.AccountInfo accounts = 1;</code>
     */
    private void clearAccounts() {
      accounts_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.github.im.common.connect.model.proto.AccountInfo accounts = 1;</code>
     */
    private void removeAccounts(int index) {
      ensureAccountsIsMutable();
      accounts_.remove(index);
    }

    public static com.github.im.common.connect.model.proto.OnLineUser.UserSearch parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.im.common.connect.model.proto.OnLineUser.UserSearch parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.OnLineUser.UserSearch parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.im.common.connect.model.proto.OnLineUser.UserSearch parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.OnLineUser.UserSearch parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.im.common.connect.model.proto.OnLineUser.UserSearch parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.OnLineUser.UserSearch parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.im.common.connect.model.proto.OnLineUser.UserSearch parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.OnLineUser.UserSearch parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.github.im.common.connect.model.proto.OnLineUser.UserSearch parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.OnLineUser.UserSearch parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.im.common.connect.model.proto.OnLineUser.UserSearch parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.github.im.common.connect.model.proto.OnLineUser.UserSearch prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.github.im.common.connect.model.proto.UserSearch}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.github.im.common.connect.model.proto.OnLineUser.UserSearch, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.im.common.connect.model.proto.UserSearch)
        com.github.im.common.connect.model.proto.OnLineUser.UserSearchOrBuilder {
      // Construct using com.github.im.common.connect.model.proto.OnLineUser.UserSearch.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .com.github.im.common.connect.model.proto.AccountInfo accounts = 1;</code>
       */
      @java.lang.Override
      public java.util.List<com.github.im.common.connect.model.proto.Account.AccountInfo> getAccountsList() {
        return java.util.Collections.unmodifiableList(
            instance.getAccountsList());
      }
      /**
       * <code>repeated .com.github.im.common.connect.model.proto.AccountInfo accounts = 1;</code>
       */
      @java.lang.Override
      public int getAccountsCount() {
        return instance.getAccountsCount();
      }/**
       * <code>repeated .com.github.im.common.connect.model.proto.AccountInfo accounts = 1;</code>
       */
      @java.lang.Override
      public com.github.im.common.connect.model.proto.Account.AccountInfo getAccounts(int index) {
        return instance.getAccounts(index);
      }
      /**
       * <code>repeated .com.github.im.common.connect.model.proto.AccountInfo accounts = 1;</code>
       */
      public Builder setAccounts(
          int index, com.github.im.common.connect.model.proto.Account.AccountInfo value) {
        copyOnWrite();
        instance.setAccounts(index, value);
        return this;
      }
      /**
       * <code>repeated .com.github.im.common.connect.model.proto.AccountInfo accounts = 1;</code>
       */
      public Builder setAccounts(
          int index, com.github.im.common.connect.model.proto.Account.AccountInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setAccounts(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.github.im.common.connect.model.proto.AccountInfo accounts = 1;</code>
       */
      public Builder addAccounts(com.github.im.common.connect.model.proto.Account.AccountInfo value) {
        copyOnWrite();
        instance.addAccounts(value);
        return this;
      }
      /**
       * <code>repeated .com.github.im.common.connect.model.proto.AccountInfo accounts = 1;</code>
       */
      public Builder addAccounts(
          int index, com.github.im.common.connect.model.proto.Account.AccountInfo value) {
        copyOnWrite();
        instance.addAccounts(index, value);
        return this;
      }
      /**
       * <code>repeated .com.github.im.common.connect.model.proto.AccountInfo accounts = 1;</code>
       */
      public Builder addAccounts(
          com.github.im.common.connect.model.proto.Account.AccountInfo.Builder builderForValue) {
        copyOnWrite();
        instance.addAccounts(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.github.im.common.connect.model.proto.AccountInfo accounts = 1;</code>
       */
      public Builder addAccounts(
          int index, com.github.im.common.connect.model.proto.Account.AccountInfo.Builder builderForValue) {
        copyOnWrite();
        instance.addAccounts(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.github.im.common.connect.model.proto.AccountInfo accounts = 1;</code>
       */
      public Builder addAllAccounts(
          java.lang.Iterable<? extends com.github.im.common.connect.model.proto.Account.AccountInfo> values) {
        copyOnWrite();
        instance.addAllAccounts(values);
        return this;
      }
      /**
       * <code>repeated .com.github.im.common.connect.model.proto.AccountInfo accounts = 1;</code>
       */
      public Builder clearAccounts() {
        copyOnWrite();
        instance.clearAccounts();
        return this;
      }
      /**
       * <code>repeated .com.github.im.common.connect.model.proto.AccountInfo accounts = 1;</code>
       */
      public Builder removeAccounts(int index) {
        copyOnWrite();
        instance.removeAccounts(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.github.im.common.connect.model.proto.UserSearch)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.github.im.common.connect.model.proto.OnLineUser.UserSearch();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "accounts_",
              com.github.im.common.connect.model.proto.Account.AccountInfo.class,
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.github.im.common.connect.model.proto.OnLineUser.UserSearch> parser = PARSER;
          if (parser == null) {
            synchronized (com.github.im.common.connect.model.proto.OnLineUser.UserSearch.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.github.im.common.connect.model.proto.OnLineUser.UserSearch>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.github.im.common.connect.model.proto.UserSearch)
    private static final com.github.im.common.connect.model.proto.OnLineUser.UserSearch DEFAULT_INSTANCE;
    static {
      UserSearch defaultInstance = new UserSearch();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        UserSearch.class, defaultInstance);
    }

    public static com.github.im.common.connect.model.proto.OnLineUser.UserSearch getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<UserSearch> PARSER;

    public static com.google.protobuf.Parser<UserSearch> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
