// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageEnum.proto

package com.github.im.common.connect.model.proto;

public final class ProtocolType {
  private ProtocolType() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code com.github.im.common.connect.model.proto.ProtocolMessageEnum}
   */
  public enum ProtocolMessageEnum
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>TMP = 0;</code>
     */
    TMP(0),
    /**
     * <code>AUTH = 1001;</code>
     */
    AUTH(1001),
    /**
     * <code>ACCOUNTINFO = 1004;</code>
     */
    ACCOUNTINFO(1004),
    /**
     * <code>CHAT = 1002;</code>
     */
    CHAT(1002),
    /**
     * <code>REQUEST = 1003;</code>
     */
    REQUEST(1003),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TMP = 0;</code>
     */
    public static final int TMP_VALUE = 0;
    /**
     * <code>AUTH = 1001;</code>
     */
    public static final int AUTH_VALUE = 1001;
    /**
     * <code>ACCOUNTINFO = 1004;</code>
     */
    public static final int ACCOUNTINFO_VALUE = 1004;
    /**
     * <code>CHAT = 1002;</code>
     */
    public static final int CHAT_VALUE = 1002;
    /**
     * <code>REQUEST = 1003;</code>
     */
    public static final int REQUEST_VALUE = 1003;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ProtocolMessageEnum valueOf(int value) {
      return forNumber(value);
    }

    public static ProtocolMessageEnum forNumber(int value) {
      switch (value) {
        case 0: return TMP;
        case 1001: return AUTH;
        case 1004: return ACCOUNTINFO;
        case 1002: return CHAT;
        case 1003: return REQUEST;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProtocolMessageEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ProtocolMessageEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProtocolMessageEnum>() {
            @java.lang.Override
            public ProtocolMessageEnum findValueByNumber(int number) {
              return ProtocolMessageEnum.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return ProtocolMessageEnumVerifier.INSTANCE;
    }

    private static final class ProtocolMessageEnumVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new ProtocolMessageEnumVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return ProtocolMessageEnum.forNumber(number) != null;
            }
          };

    private final int value;

    private ProtocolMessageEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.github.im.common.connect.model.proto.ProtocolMessageEnum)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
