-- Core tenant baseline: automation, bot, conversation and department tables.
-- Schema-relative; global identity remains in public.*.

CREATE TABLE "approval_requests" (
    "approval_id" bigint NOT NULL,
    "created_at" timestamp(6) without time zone,
    "decided_at" timestamp(6) without time zone,
    "expires_at" timestamp(6) without time zone NOT NULL,
    "status" character varying(32) NOT NULL,
    "execution_id" bigint NOT NULL,
    "requested_by_user_id" bigint NOT NULL,
    CONSTRAINT "approval_requests_status_check" CHECK ((("status")::"text" = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'DECLINED'::character varying])::"text"[])))
);

ALTER TABLE "approval_requests" ALTER COLUMN "approval_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "approval_requests_approval_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "automation_executions" (
    "execution_id" bigint NOT NULL,
    "action_type" character varying(64) NOT NULL,
    "created_at" timestamp(6) without time zone,
    "idempotency_key" character varying(100) NOT NULL,
    "payload" "text",
    "result_message_id" bigint,
    "result_summary" character varying(512),
    "status" character varying(32) NOT NULL,
    "summary" character varying(512) NOT NULL,
    "updated_at" timestamp(6) without time zone,
    "conversation_id" bigint,
    "requested_by_user_id" bigint NOT NULL,
    "rule_id" bigint,
    CONSTRAINT "automation_executions_status_check" CHECK ((("status")::"text" = ANY ((ARRAY['PENDING_APPROVAL'::character varying, 'APPROVED'::character varying, 'DECLINED'::character varying, 'EXECUTED'::character varying, 'FAILED'::character varying])::"text"[])))
);

ALTER TABLE "automation_executions" ALTER COLUMN "execution_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "automation_executions_execution_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "automation_rules" (
    "rule_id" bigint NOT NULL,
    "action_type" character varying(64) NOT NULL,
    "configuration" "text",
    "created_at" timestamp(6) without time zone,
    "enabled" boolean NOT NULL,
    "trigger_type" character varying(64) NOT NULL,
    "updated_at" timestamp(6) without time zone,
    "conversation_id" bigint,
    "owner_user_id" bigint NOT NULL
);

ALTER TABLE "automation_rules" ALTER COLUMN "rule_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "automation_rules_rule_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "conversation_bot_configs" (
    "config_id" bigint NOT NULL,
    "created_at" timestamp(6) without time zone,
    "enabled" boolean NOT NULL,
    "prompt_template" "text",
    "updated_at" timestamp(6) without time zone,
    "conversation_id" bigint NOT NULL,
    "updated_by_user_id" bigint NOT NULL
);

ALTER TABLE "conversation_bot_configs" ALTER COLUMN "config_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "conversation_bot_configs_config_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "conversation_members" (
    "id" bigint NOT NULL,
    "joined_at" timestamp(6) without time zone,
    "left_at" timestamp(6) without time zone,
    "conversation_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "last_read_sequence_id" bigint,
    "role" character varying,
    CONSTRAINT "conversation_members_role_check" CHECK ((("role")::"text" = ANY (ARRAY[('OWNER'::character varying)::"text", ('ADMIN'::character varying)::"text", ('MEMBER'::character varying)::"text"])))
);

ALTER TABLE "conversation_members" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "conversation_members_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "conversations" (
    "conversation_id" bigint NOT NULL,
    "conversation_type" character varying(255) NOT NULL,
    "created_at" timestamp(6) without time zone,
    "description" character varying(255),
    "group_name" character varying(255),
    "status" character varying(255) NOT NULL,
    "updated_at" timestamp(6) without time zone,
    "created_by" bigint NOT NULL,
    CONSTRAINT "conversations_conversation_type_check" CHECK ((("conversation_type")::"text" = ANY ((ARRAY['GROUP'::character varying, 'PRIVATE_CHAT'::character varying])::"text"[]))),
    CONSTRAINT "conversations_status_check" CHECK ((("status")::"text" = ANY ((ARRAY['ACTIVE'::character varying, 'ACHEIVED'::character varying, 'DELETED'::character varying, 'INACTIVE'::character varying])::"text"[])))
);

ALTER TABLE "conversations" ALTER COLUMN "conversation_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "conversations_conversation_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "departments" (
    "department_id" bigint NOT NULL,
    "company_id" bigint NOT NULL,
    "created_at" timestamp(6) without time zone,
    "description" character varying(500),
    "name" character varying(255) NOT NULL,
    "order_num" integer,
    "parent_id" bigint,
    "status" boolean NOT NULL,
    "updated_at" timestamp(6) without time zone
);

ALTER TABLE "departments" ALTER COLUMN "department_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "departments_department_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
