-- Core tenant baseline: file, friendship and meeting tables.
-- Schema-relative; foreign keys are added in a later migration.

CREATE TABLE "file_resource" (
    "id" "uuid" NOT NULL,
    "content_type" character varying(255),
    "extension" character varying(255),
    "hash" character varying(255),
    "original_name" character varying(255),
    "remark" character varying(255),
    "size" bigint NOT NULL,
    "status" character varying(255),
    "storage_path" character varying(255),
    "storage_type" character varying(255),
    "upload_time" timestamp(6) without time zone,
    CONSTRAINT "file_resource_status_check" CHECK ((("status")::"text" = ANY ((ARRAY['UPLOADING'::character varying, 'NORMAL'::character varying, 'DELETED'::character varying, 'EXPIRED'::character varying, 'FAILED'::character varying, 'CHUNK_UPLOADING'::character varying])::"text"[]))),
    CONSTRAINT "file_resource_storage_type_check" CHECK ((("storage_type")::"text" = ANY ((ARRAY['LOCAL'::character varying, 'OSS'::character varying])::"text"[])))
);

CREATE TABLE "friendships" (
    "id" bigint NOT NULL,
    "apply_remark" character varying(255),
    "created_at" timestamp(6) without time zone,
    "remark" character varying(255),
    "status" character varying(255),
    "updated_at" timestamp(6) without time zone,
    "friend_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    CONSTRAINT "friendships_status_check" CHECK ((("status")::"text" = ANY ((ARRAY['PENDING'::character varying, 'ACTIVE'::character varying, 'REJECT'::character varying, 'DISCARD'::character varying, 'DELETED'::character varying, 'BLOCKED'::character varying])::"text"[])))
);

ALTER TABLE "friendships" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "friendships_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "media_file_resource" (
    "id" bigint NOT NULL,
    "duration" double precision DEFAULT 0 NOT NULL,
    "thumbnail" character varying(255),
    "file_id" "uuid" NOT NULL
);

ALTER TABLE "media_file_resource" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "media_file_resource_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "meeting_participants" (
    "id" bigint NOT NULL,
    "created_at" timestamp(6) without time zone,
    "joined_at" timestamp(6) without time zone,
    "left_at" timestamp(6) without time zone,
    "role" character varying(255) NOT NULL,
    "status" character varying(255) NOT NULL,
    "updated_at" timestamp(6) without time zone,
    "meeting_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    CONSTRAINT "meeting_participants_role_check" CHECK ((("role")::"text" = ANY ((ARRAY['HOST'::character varying, 'PARTICIPANT'::character varying])::"text"[]))),
    CONSTRAINT "meeting_participants_status_check" CHECK ((("status")::"text" = ANY ((ARRAY['INVITED'::character varying, 'JOINED'::character varying, 'LEFT'::character varying, 'REJECTED'::character varying])::"text"[])))
);

ALTER TABLE "meeting_participants" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "meeting_participants_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "meetings" (
    "meeting_id" bigint NOT NULL,
    "created_at" timestamp(6) without time zone,
    "ended_at" timestamp(6) without time zone,
    "room_id" character varying(255) NOT NULL,
    "started_at" timestamp(6) without time zone,
    "status" character varying(255) NOT NULL,
    "title" character varying(255),
    "updated_at" timestamp(6) without time zone,
    "conversation_id" bigint NOT NULL,
    "created_by" bigint NOT NULL,
    "ended_by" bigint,
    "scheduled_at" timestamp(6) without time zone,
    CONSTRAINT "meetings_status_check" CHECK ((("status")::"text" = ANY (ARRAY[('ACTIVE'::character varying)::"text", ('ENDED'::character varying)::"text", ('CANCELED'::character varying)::"text", ('SCHEDULED'::character varying)::"text"])))
);

ALTER TABLE "meetings" ALTER COLUMN "meeting_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "meetings_meeting_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
