-- Core tenant baseline: messaging, status, config, upload and user-association tables.
-- Schema-relative; foreign keys are added in a later migration.

CREATE TABLE "messages" (
    "msg_id" bigint NOT NULL,
    "client_msg_id" character varying(255),
    "client_timestamp" timestamp(6) without time zone,
    "content" "text",
    "create_time" timestamp(6) without time zone,
    "sequence_id" bigint DEFAULT 0 NOT NULL,
    "status" character varying(255),
    "timestamp" timestamp(6) without time zone,
    "type" character varying(255),
    "conversation_id" bigint NOT NULL,
    "from_account_id" bigint NOT NULL,
    CONSTRAINT "messages_status_check" CHECK ((("status")::"text" = ANY ((ARRAY['SENDING'::character varying, 'SENT'::character varying, 'RECEIVED'::character varying, 'FAILED'::character varying, 'READ'::character varying, 'UNREAD'::character varying, 'DELETED'::character varying, 'REVOKE'::character varying])::"text"[]))),
    CONSTRAINT "messages_type_check" CHECK ((("type")::"text" = ANY (ARRAY[('TEXT'::character varying)::"text", ('FILE'::character varying)::"text", ('VOICE'::character varying)::"text", ('VIDEO'::character varying)::"text", ('IMAGE'::character varying)::"text", ('MEDIA'::character varying)::"text", ('MEETING'::character varying)::"text", ('BOT_CARD'::character varying)::"text"])))
);

ALTER TABLE "messages" ALTER COLUMN "msg_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "messages_msg_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "status_updates" (
    "id" bigint NOT NULL,
    "content" character varying(255) NOT NULL,
    "created_at" timestamp(6) without time zone,
    "user_id" bigint NOT NULL
);

ALTER TABLE "status_updates" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "status_updates_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "system_config_item" (
    "id" bigint NOT NULL,
    "config_group" character varying(60) NOT NULL,
    "config_key" character varying(120) NOT NULL,
    "config_value" character varying(255) NOT NULL,
    "created_at" timestamp(6) without time zone NOT NULL,
    "default_value" character varying(255) NOT NULL,
    "description" character varying(500),
    "public_readable" boolean NOT NULL,
    "updated_at" timestamp(6) without time zone NOT NULL,
    "value_type" character varying(30) NOT NULL
);

ALTER TABLE "system_config_item" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "system_config_item_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "upload_chunk_record" (
    "id" bigint NOT NULL,
    "chunk_index" integer,
    "create_time" bigint,
    "file_hash" character varying(64) NOT NULL,
    "temp_path" character varying(255),
    "total_chunks" integer,
    "uploaded" boolean NOT NULL,
    "uploader_id" "uuid"
);

ALTER TABLE "upload_chunk_record" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "upload_chunk_record_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "user_departments" (
    "id" bigint NOT NULL,
    "created_at" timestamp(6) without time zone NOT NULL,
    "department_id" bigint NOT NULL,
    "user_id" bigint NOT NULL
);

ALTER TABLE "user_departments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "user_departments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "user_privacy_settings" (
    "setting_id" bigint NOT NULL,
    "allow_friend_request" boolean,
    "notification_preference" character varying(255) NOT NULL,
    "show_last_online_time" boolean,
    "visibility_status" boolean,
    "user_id" bigint
);

ALTER TABLE "user_privacy_settings" ALTER COLUMN "setting_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "user_privacy_settings_setting_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
