package com.github.im.server.workbench.common.error;

public enum WorkbenchErrorCode {
    AUTHENTICATION_REQUIRED,
    CURRENT_COMPANY_REQUIRED,
    COMPANY_INACTIVE,
    INVALID_TENANT_SCOPE,
    TENANT_CONTEXT_MISMATCH,
    PERMISSION_DENIED,
    PERMISSION_POLICY_MISSING,
    MEMBER_NOT_FOUND,
    FILE_NOT_AVAILABLE,
    TASK_NOT_FOUND,
    TASK_ACCESS_DENIED,
    TASK_INVALID_REQUEST,
    TASK_INVALID_TRANSITION,
    TASK_ASSIGNEE_INVALID,
    TASK_COMMENT_INVALID;

    public String code() {
        return "WORKBENCH_" + name();
    }
}
