// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: BaseMessage.proto
// Protobuf Java Version: 4.28.2

package com.github.im.common.connect.model.proto;

public final class BaseMessage {
  private BaseMessage() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      BaseMessage.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BaseMessagePkgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.im.common.connect.model.proto.BaseMessagePkg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
     * @return Whether the accountInfo field is set.
     */
    boolean hasAccountInfo();
    /**
     * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
     * @return The accountInfo.
     */
    com.github.im.common.connect.model.proto.Account.AccountInfo getAccountInfo();
    /**
     * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
     */
    com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder getAccountInfoOrBuilder();

    /**
     * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
     * @return Whether the message field is set.
     */
    boolean hasMessage();
    /**
     * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
     * @return The message.
     */
    com.github.im.common.connect.model.proto.Chat.ChatMessage getMessage();
    /**
     * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
     */
    com.github.im.common.connect.model.proto.Chat.ChatMessageOrBuilder getMessageOrBuilder();

    /**
     * <code>.com.github.im.common.connect.model.proto.NotificationInfo notification = 3;</code>
     * @return Whether the notification field is set.
     */
    boolean hasNotification();
    /**
     * <code>.com.github.im.common.connect.model.proto.NotificationInfo notification = 3;</code>
     * @return The notification.
     */
    com.github.im.common.connect.model.proto.Notification.NotificationInfo getNotification();
    /**
     * <code>.com.github.im.common.connect.model.proto.NotificationInfo notification = 3;</code>
     */
    com.github.im.common.connect.model.proto.Notification.NotificationInfoOrBuilder getNotificationOrBuilder();

    /**
     * <code>.com.github.im.common.connect.model.proto.AckMessage ack = 4;</code>
     * @return Whether the ack field is set.
     */
    boolean hasAck();
    /**
     * <code>.com.github.im.common.connect.model.proto.AckMessage ack = 4;</code>
     * @return The ack.
     */
    com.github.im.common.connect.model.proto.Chat.AckMessage getAck();
    /**
     * <code>.com.github.im.common.connect.model.proto.AckMessage ack = 4;</code>
     */
    com.github.im.common.connect.model.proto.Chat.AckMessageOrBuilder getAckOrBuilder();

    /**
     * <code>.com.github.im.common.connect.model.proto.Heartbeat heartbeat = 5;</code>
     * @return Whether the heartbeat field is set.
     */
    boolean hasHeartbeat();
    /**
     * <code>.com.github.im.common.connect.model.proto.Heartbeat heartbeat = 5;</code>
     * @return The heartbeat.
     */
    com.github.im.common.connect.model.proto.BaseMessage.Heartbeat getHeartbeat();
    /**
     * <code>.com.github.im.common.connect.model.proto.Heartbeat heartbeat = 5;</code>
     */
    com.github.im.common.connect.model.proto.BaseMessage.HeartbeatOrBuilder getHeartbeatOrBuilder();

    com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg.PayloadCase getPayloadCase();
  }
  /**
   * Protobuf type {@code com.github.im.common.connect.model.proto.BaseMessagePkg}
   */
  public static final class BaseMessagePkg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.github.im.common.connect.model.proto.BaseMessagePkg)
      BaseMessagePkgOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        BaseMessagePkg.class.getName());
    }
    // Use BaseMessagePkg.newBuilder() to construct.
    private BaseMessagePkg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private BaseMessagePkg() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.im.common.connect.model.proto.BaseMessage.internal_static_com_github_im_common_connect_model_proto_BaseMessagePkg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.im.common.connect.model.proto.BaseMessage.internal_static_com_github_im_common_connect_model_proto_BaseMessagePkg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg.class, com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg.Builder.class);
    }

    private int payloadCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object payload_;
    public enum PayloadCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      ACCOUNTINFO(1),
      MESSAGE(2),
      NOTIFICATION(3),
      ACK(4),
      HEARTBEAT(5),
      PAYLOAD_NOT_SET(0);
      private final int value;
      private PayloadCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PayloadCase valueOf(int value) {
        return forNumber(value);
      }

      public static PayloadCase forNumber(int value) {
        switch (value) {
          case 1: return ACCOUNTINFO;
          case 2: return MESSAGE;
          case 3: return NOTIFICATION;
          case 4: return ACK;
          case 5: return HEARTBEAT;
          case 0: return PAYLOAD_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PayloadCase
    getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public static final int ACCOUNTINFO_FIELD_NUMBER = 1;
    /**
     * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
     * @return Whether the accountInfo field is set.
     */
    @java.lang.Override
    public boolean hasAccountInfo() {
      return payloadCase_ == 1;
    }
    /**
     * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
     * @return The accountInfo.
     */
    @java.lang.Override
    public com.github.im.common.connect.model.proto.Account.AccountInfo getAccountInfo() {
      if (payloadCase_ == 1) {
         return (com.github.im.common.connect.model.proto.Account.AccountInfo) payload_;
      }
      return com.github.im.common.connect.model.proto.Account.AccountInfo.getDefaultInstance();
    }
    /**
     * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
     */
    @java.lang.Override
    public com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder getAccountInfoOrBuilder() {
      if (payloadCase_ == 1) {
         return (com.github.im.common.connect.model.proto.Account.AccountInfo) payload_;
      }
      return com.github.im.common.connect.model.proto.Account.AccountInfo.getDefaultInstance();
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    /**
     * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
     * @return Whether the message field is set.
     */
    @java.lang.Override
    public boolean hasMessage() {
      return payloadCase_ == 2;
    }
    /**
     * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public com.github.im.common.connect.model.proto.Chat.ChatMessage getMessage() {
      if (payloadCase_ == 2) {
         return (com.github.im.common.connect.model.proto.Chat.ChatMessage) payload_;
      }
      return com.github.im.common.connect.model.proto.Chat.ChatMessage.getDefaultInstance();
    }
    /**
     * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
     */
    @java.lang.Override
    public com.github.im.common.connect.model.proto.Chat.ChatMessageOrBuilder getMessageOrBuilder() {
      if (payloadCase_ == 2) {
         return (com.github.im.common.connect.model.proto.Chat.ChatMessage) payload_;
      }
      return com.github.im.common.connect.model.proto.Chat.ChatMessage.getDefaultInstance();
    }

    public static final int NOTIFICATION_FIELD_NUMBER = 3;
    /**
     * <code>.com.github.im.common.connect.model.proto.NotificationInfo notification = 3;</code>
     * @return Whether the notification field is set.
     */
    @java.lang.Override
    public boolean hasNotification() {
      return payloadCase_ == 3;
    }
    /**
     * <code>.com.github.im.common.connect.model.proto.NotificationInfo notification = 3;</code>
     * @return The notification.
     */
    @java.lang.Override
    public com.github.im.common.connect.model.proto.Notification.NotificationInfo getNotification() {
      if (payloadCase_ == 3) {
         return (com.github.im.common.connect.model.proto.Notification.NotificationInfo) payload_;
      }
      return com.github.im.common.connect.model.proto.Notification.NotificationInfo.getDefaultInstance();
    }
    /**
     * <code>.com.github.im.common.connect.model.proto.NotificationInfo notification = 3;</code>
     */
    @java.lang.Override
    public com.github.im.common.connect.model.proto.Notification.NotificationInfoOrBuilder getNotificationOrBuilder() {
      if (payloadCase_ == 3) {
         return (com.github.im.common.connect.model.proto.Notification.NotificationInfo) payload_;
      }
      return com.github.im.common.connect.model.proto.Notification.NotificationInfo.getDefaultInstance();
    }

    public static final int ACK_FIELD_NUMBER = 4;
    /**
     * <code>.com.github.im.common.connect.model.proto.AckMessage ack = 4;</code>
     * @return Whether the ack field is set.
     */
    @java.lang.Override
    public boolean hasAck() {
      return payloadCase_ == 4;
    }
    /**
     * <code>.com.github.im.common.connect.model.proto.AckMessage ack = 4;</code>
     * @return The ack.
     */
    @java.lang.Override
    public com.github.im.common.connect.model.proto.Chat.AckMessage getAck() {
      if (payloadCase_ == 4) {
         return (com.github.im.common.connect.model.proto.Chat.AckMessage) payload_;
      }
      return com.github.im.common.connect.model.proto.Chat.AckMessage.getDefaultInstance();
    }
    /**
     * <code>.com.github.im.common.connect.model.proto.AckMessage ack = 4;</code>
     */
    @java.lang.Override
    public com.github.im.common.connect.model.proto.Chat.AckMessageOrBuilder getAckOrBuilder() {
      if (payloadCase_ == 4) {
         return (com.github.im.common.connect.model.proto.Chat.AckMessage) payload_;
      }
      return com.github.im.common.connect.model.proto.Chat.AckMessage.getDefaultInstance();
    }

    public static final int HEARTBEAT_FIELD_NUMBER = 5;
    /**
     * <code>.com.github.im.common.connect.model.proto.Heartbeat heartbeat = 5;</code>
     * @return Whether the heartbeat field is set.
     */
    @java.lang.Override
    public boolean hasHeartbeat() {
      return payloadCase_ == 5;
    }
    /**
     * <code>.com.github.im.common.connect.model.proto.Heartbeat heartbeat = 5;</code>
     * @return The heartbeat.
     */
    @java.lang.Override
    public com.github.im.common.connect.model.proto.BaseMessage.Heartbeat getHeartbeat() {
      if (payloadCase_ == 5) {
         return (com.github.im.common.connect.model.proto.BaseMessage.Heartbeat) payload_;
      }
      return com.github.im.common.connect.model.proto.BaseMessage.Heartbeat.getDefaultInstance();
    }
    /**
     * <code>.com.github.im.common.connect.model.proto.Heartbeat heartbeat = 5;</code>
     */
    @java.lang.Override
    public com.github.im.common.connect.model.proto.BaseMessage.HeartbeatOrBuilder getHeartbeatOrBuilder() {
      if (payloadCase_ == 5) {
         return (com.github.im.common.connect.model.proto.BaseMessage.Heartbeat) payload_;
      }
      return com.github.im.common.connect.model.proto.BaseMessage.Heartbeat.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (payloadCase_ == 1) {
        output.writeMessage(1, (com.github.im.common.connect.model.proto.Account.AccountInfo) payload_);
      }
      if (payloadCase_ == 2) {
        output.writeMessage(2, (com.github.im.common.connect.model.proto.Chat.ChatMessage) payload_);
      }
      if (payloadCase_ == 3) {
        output.writeMessage(3, (com.github.im.common.connect.model.proto.Notification.NotificationInfo) payload_);
      }
      if (payloadCase_ == 4) {
        output.writeMessage(4, (com.github.im.common.connect.model.proto.Chat.AckMessage) payload_);
      }
      if (payloadCase_ == 5) {
        output.writeMessage(5, (com.github.im.common.connect.model.proto.BaseMessage.Heartbeat) payload_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (payloadCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (com.github.im.common.connect.model.proto.Account.AccountInfo) payload_);
      }
      if (payloadCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.github.im.common.connect.model.proto.Chat.ChatMessage) payload_);
      }
      if (payloadCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.github.im.common.connect.model.proto.Notification.NotificationInfo) payload_);
      }
      if (payloadCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (com.github.im.common.connect.model.proto.Chat.AckMessage) payload_);
      }
      if (payloadCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, (com.github.im.common.connect.model.proto.BaseMessage.Heartbeat) payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg)) {
        return super.equals(obj);
      }
      com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg other = (com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg) obj;

      if (!getPayloadCase().equals(other.getPayloadCase())) return false;
      switch (payloadCase_) {
        case 1:
          if (!getAccountInfo()
              .equals(other.getAccountInfo())) return false;
          break;
        case 2:
          if (!getMessage()
              .equals(other.getMessage())) return false;
          break;
        case 3:
          if (!getNotification()
              .equals(other.getNotification())) return false;
          break;
        case 4:
          if (!getAck()
              .equals(other.getAck())) return false;
          break;
        case 5:
          if (!getHeartbeat()
              .equals(other.getHeartbeat())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (payloadCase_) {
        case 1:
          hash = (37 * hash) + ACCOUNTINFO_FIELD_NUMBER;
          hash = (53 * hash) + getAccountInfo().hashCode();
          break;
        case 2:
          hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getMessage().hashCode();
          break;
        case 3:
          hash = (37 * hash) + NOTIFICATION_FIELD_NUMBER;
          hash = (53 * hash) + getNotification().hashCode();
          break;
        case 4:
          hash = (37 * hash) + ACK_FIELD_NUMBER;
          hash = (53 * hash) + getAck().hashCode();
          break;
        case 5:
          hash = (37 * hash) + HEARTBEAT_FIELD_NUMBER;
          hash = (53 * hash) + getHeartbeat().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.im.common.connect.model.proto.BaseMessagePkg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.im.common.connect.model.proto.BaseMessagePkg)
        com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.im.common.connect.model.proto.BaseMessage.internal_static_com_github_im_common_connect_model_proto_BaseMessagePkg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.im.common.connect.model.proto.BaseMessage.internal_static_com_github_im_common_connect_model_proto_BaseMessagePkg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg.class, com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg.Builder.class);
      }

      // Construct using com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (accountInfoBuilder_ != null) {
          accountInfoBuilder_.clear();
        }
        if (messageBuilder_ != null) {
          messageBuilder_.clear();
        }
        if (notificationBuilder_ != null) {
          notificationBuilder_.clear();
        }
        if (ackBuilder_ != null) {
          ackBuilder_.clear();
        }
        if (heartbeatBuilder_ != null) {
          heartbeatBuilder_.clear();
        }
        payloadCase_ = 0;
        payload_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.im.common.connect.model.proto.BaseMessage.internal_static_com_github_im_common_connect_model_proto_BaseMessagePkg_descriptor;
      }

      @java.lang.Override
      public com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg getDefaultInstanceForType() {
        return com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg build() {
        com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg buildPartial() {
        com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg result = new com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg result) {
        int from_bitField0_ = bitField0_;
      }

      private void buildPartialOneofs(com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg result) {
        result.payloadCase_ = payloadCase_;
        result.payload_ = this.payload_;
        if (payloadCase_ == 1 &&
            accountInfoBuilder_ != null) {
          result.payload_ = accountInfoBuilder_.build();
        }
        if (payloadCase_ == 2 &&
            messageBuilder_ != null) {
          result.payload_ = messageBuilder_.build();
        }
        if (payloadCase_ == 3 &&
            notificationBuilder_ != null) {
          result.payload_ = notificationBuilder_.build();
        }
        if (payloadCase_ == 4 &&
            ackBuilder_ != null) {
          result.payload_ = ackBuilder_.build();
        }
        if (payloadCase_ == 5 &&
            heartbeatBuilder_ != null) {
          result.payload_ = heartbeatBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg) {
          return mergeFrom((com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg other) {
        if (other == com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg.getDefaultInstance()) return this;
        switch (other.getPayloadCase()) {
          case ACCOUNTINFO: {
            mergeAccountInfo(other.getAccountInfo());
            break;
          }
          case MESSAGE: {
            mergeMessage(other.getMessage());
            break;
          }
          case NOTIFICATION: {
            mergeNotification(other.getNotification());
            break;
          }
          case ACK: {
            mergeAck(other.getAck());
            break;
          }
          case HEARTBEAT: {
            mergeHeartbeat(other.getHeartbeat());
            break;
          }
          case PAYLOAD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getAccountInfoFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 1;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getMessageFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 2;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getNotificationFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 3;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getAckFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 4;
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    getHeartbeatFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 5;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int payloadCase_ = 0;
      private java.lang.Object payload_;
      public PayloadCase
          getPayloadCase() {
        return PayloadCase.forNumber(
            payloadCase_);
      }

      public Builder clearPayload() {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilder<
          com.github.im.common.connect.model.proto.Account.AccountInfo, com.github.im.common.connect.model.proto.Account.AccountInfo.Builder, com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder> accountInfoBuilder_;
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
       * @return Whether the accountInfo field is set.
       */
      @java.lang.Override
      public boolean hasAccountInfo() {
        return payloadCase_ == 1;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
       * @return The accountInfo.
       */
      @java.lang.Override
      public com.github.im.common.connect.model.proto.Account.AccountInfo getAccountInfo() {
        if (accountInfoBuilder_ == null) {
          if (payloadCase_ == 1) {
            return (com.github.im.common.connect.model.proto.Account.AccountInfo) payload_;
          }
          return com.github.im.common.connect.model.proto.Account.AccountInfo.getDefaultInstance();
        } else {
          if (payloadCase_ == 1) {
            return accountInfoBuilder_.getMessage();
          }
          return com.github.im.common.connect.model.proto.Account.AccountInfo.getDefaultInstance();
        }
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
       */
      public Builder setAccountInfo(com.github.im.common.connect.model.proto.Account.AccountInfo value) {
        if (accountInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          accountInfoBuilder_.setMessage(value);
        }
        payloadCase_ = 1;
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
       */
      public Builder setAccountInfo(
          com.github.im.common.connect.model.proto.Account.AccountInfo.Builder builderForValue) {
        if (accountInfoBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          accountInfoBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 1;
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
       */
      public Builder mergeAccountInfo(com.github.im.common.connect.model.proto.Account.AccountInfo value) {
        if (accountInfoBuilder_ == null) {
          if (payloadCase_ == 1 &&
              payload_ != com.github.im.common.connect.model.proto.Account.AccountInfo.getDefaultInstance()) {
            payload_ = com.github.im.common.connect.model.proto.Account.AccountInfo.newBuilder((com.github.im.common.connect.model.proto.Account.AccountInfo) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 1) {
            accountInfoBuilder_.mergeFrom(value);
          } else {
            accountInfoBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 1;
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
       */
      public Builder clearAccountInfo() {
        if (accountInfoBuilder_ == null) {
          if (payloadCase_ == 1) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 1) {
            payloadCase_ = 0;
            payload_ = null;
          }
          accountInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
       */
      public com.github.im.common.connect.model.proto.Account.AccountInfo.Builder getAccountInfoBuilder() {
        return getAccountInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
       */
      @java.lang.Override
      public com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder getAccountInfoOrBuilder() {
        if ((payloadCase_ == 1) && (accountInfoBuilder_ != null)) {
          return accountInfoBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 1) {
            return (com.github.im.common.connect.model.proto.Account.AccountInfo) payload_;
          }
          return com.github.im.common.connect.model.proto.Account.AccountInfo.getDefaultInstance();
        }
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.github.im.common.connect.model.proto.Account.AccountInfo, com.github.im.common.connect.model.proto.Account.AccountInfo.Builder, com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder> 
          getAccountInfoFieldBuilder() {
        if (accountInfoBuilder_ == null) {
          if (!(payloadCase_ == 1)) {
            payload_ = com.github.im.common.connect.model.proto.Account.AccountInfo.getDefaultInstance();
          }
          accountInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.github.im.common.connect.model.proto.Account.AccountInfo, com.github.im.common.connect.model.proto.Account.AccountInfo.Builder, com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder>(
                  (com.github.im.common.connect.model.proto.Account.AccountInfo) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 1;
        onChanged();
        return accountInfoBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          com.github.im.common.connect.model.proto.Chat.ChatMessage, com.github.im.common.connect.model.proto.Chat.ChatMessage.Builder, com.github.im.common.connect.model.proto.Chat.ChatMessageOrBuilder> messageBuilder_;
      /**
       * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
       * @return Whether the message field is set.
       */
      @java.lang.Override
      public boolean hasMessage() {
        return payloadCase_ == 2;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
       * @return The message.
       */
      @java.lang.Override
      public com.github.im.common.connect.model.proto.Chat.ChatMessage getMessage() {
        if (messageBuilder_ == null) {
          if (payloadCase_ == 2) {
            return (com.github.im.common.connect.model.proto.Chat.ChatMessage) payload_;
          }
          return com.github.im.common.connect.model.proto.Chat.ChatMessage.getDefaultInstance();
        } else {
          if (payloadCase_ == 2) {
            return messageBuilder_.getMessage();
          }
          return com.github.im.common.connect.model.proto.Chat.ChatMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
       */
      public Builder setMessage(com.github.im.common.connect.model.proto.Chat.ChatMessage value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          messageBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
       */
      public Builder setMessage(
          com.github.im.common.connect.model.proto.Chat.ChatMessage.Builder builderForValue) {
        if (messageBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          messageBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
       */
      public Builder mergeMessage(com.github.im.common.connect.model.proto.Chat.ChatMessage value) {
        if (messageBuilder_ == null) {
          if (payloadCase_ == 2 &&
              payload_ != com.github.im.common.connect.model.proto.Chat.ChatMessage.getDefaultInstance()) {
            payload_ = com.github.im.common.connect.model.proto.Chat.ChatMessage.newBuilder((com.github.im.common.connect.model.proto.Chat.ChatMessage) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 2) {
            messageBuilder_.mergeFrom(value);
          } else {
            messageBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
       */
      public Builder clearMessage() {
        if (messageBuilder_ == null) {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
          }
          messageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
       */
      public com.github.im.common.connect.model.proto.Chat.ChatMessage.Builder getMessageBuilder() {
        return getMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
       */
      @java.lang.Override
      public com.github.im.common.connect.model.proto.Chat.ChatMessageOrBuilder getMessageOrBuilder() {
        if ((payloadCase_ == 2) && (messageBuilder_ != null)) {
          return messageBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 2) {
            return (com.github.im.common.connect.model.proto.Chat.ChatMessage) payload_;
          }
          return com.github.im.common.connect.model.proto.Chat.ChatMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.github.im.common.connect.model.proto.Chat.ChatMessage, com.github.im.common.connect.model.proto.Chat.ChatMessage.Builder, com.github.im.common.connect.model.proto.Chat.ChatMessageOrBuilder> 
          getMessageFieldBuilder() {
        if (messageBuilder_ == null) {
          if (!(payloadCase_ == 2)) {
            payload_ = com.github.im.common.connect.model.proto.Chat.ChatMessage.getDefaultInstance();
          }
          messageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.github.im.common.connect.model.proto.Chat.ChatMessage, com.github.im.common.connect.model.proto.Chat.ChatMessage.Builder, com.github.im.common.connect.model.proto.Chat.ChatMessageOrBuilder>(
                  (com.github.im.common.connect.model.proto.Chat.ChatMessage) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 2;
        onChanged();
        return messageBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          com.github.im.common.connect.model.proto.Notification.NotificationInfo, com.github.im.common.connect.model.proto.Notification.NotificationInfo.Builder, com.github.im.common.connect.model.proto.Notification.NotificationInfoOrBuilder> notificationBuilder_;
      /**
       * <code>.com.github.im.common.connect.model.proto.NotificationInfo notification = 3;</code>
       * @return Whether the notification field is set.
       */
      @java.lang.Override
      public boolean hasNotification() {
        return payloadCase_ == 3;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.NotificationInfo notification = 3;</code>
       * @return The notification.
       */
      @java.lang.Override
      public com.github.im.common.connect.model.proto.Notification.NotificationInfo getNotification() {
        if (notificationBuilder_ == null) {
          if (payloadCase_ == 3) {
            return (com.github.im.common.connect.model.proto.Notification.NotificationInfo) payload_;
          }
          return com.github.im.common.connect.model.proto.Notification.NotificationInfo.getDefaultInstance();
        } else {
          if (payloadCase_ == 3) {
            return notificationBuilder_.getMessage();
          }
          return com.github.im.common.connect.model.proto.Notification.NotificationInfo.getDefaultInstance();
        }
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.NotificationInfo notification = 3;</code>
       */
      public Builder setNotification(com.github.im.common.connect.model.proto.Notification.NotificationInfo value) {
        if (notificationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          notificationBuilder_.setMessage(value);
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.NotificationInfo notification = 3;</code>
       */
      public Builder setNotification(
          com.github.im.common.connect.model.proto.Notification.NotificationInfo.Builder builderForValue) {
        if (notificationBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          notificationBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.NotificationInfo notification = 3;</code>
       */
      public Builder mergeNotification(com.github.im.common.connect.model.proto.Notification.NotificationInfo value) {
        if (notificationBuilder_ == null) {
          if (payloadCase_ == 3 &&
              payload_ != com.github.im.common.connect.model.proto.Notification.NotificationInfo.getDefaultInstance()) {
            payload_ = com.github.im.common.connect.model.proto.Notification.NotificationInfo.newBuilder((com.github.im.common.connect.model.proto.Notification.NotificationInfo) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 3) {
            notificationBuilder_.mergeFrom(value);
          } else {
            notificationBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.NotificationInfo notification = 3;</code>
       */
      public Builder clearNotification() {
        if (notificationBuilder_ == null) {
          if (payloadCase_ == 3) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 3) {
            payloadCase_ = 0;
            payload_ = null;
          }
          notificationBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.NotificationInfo notification = 3;</code>
       */
      public com.github.im.common.connect.model.proto.Notification.NotificationInfo.Builder getNotificationBuilder() {
        return getNotificationFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.NotificationInfo notification = 3;</code>
       */
      @java.lang.Override
      public com.github.im.common.connect.model.proto.Notification.NotificationInfoOrBuilder getNotificationOrBuilder() {
        if ((payloadCase_ == 3) && (notificationBuilder_ != null)) {
          return notificationBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 3) {
            return (com.github.im.common.connect.model.proto.Notification.NotificationInfo) payload_;
          }
          return com.github.im.common.connect.model.proto.Notification.NotificationInfo.getDefaultInstance();
        }
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.NotificationInfo notification = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.github.im.common.connect.model.proto.Notification.NotificationInfo, com.github.im.common.connect.model.proto.Notification.NotificationInfo.Builder, com.github.im.common.connect.model.proto.Notification.NotificationInfoOrBuilder> 
          getNotificationFieldBuilder() {
        if (notificationBuilder_ == null) {
          if (!(payloadCase_ == 3)) {
            payload_ = com.github.im.common.connect.model.proto.Notification.NotificationInfo.getDefaultInstance();
          }
          notificationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.github.im.common.connect.model.proto.Notification.NotificationInfo, com.github.im.common.connect.model.proto.Notification.NotificationInfo.Builder, com.github.im.common.connect.model.proto.Notification.NotificationInfoOrBuilder>(
                  (com.github.im.common.connect.model.proto.Notification.NotificationInfo) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 3;
        onChanged();
        return notificationBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          com.github.im.common.connect.model.proto.Chat.AckMessage, com.github.im.common.connect.model.proto.Chat.AckMessage.Builder, com.github.im.common.connect.model.proto.Chat.AckMessageOrBuilder> ackBuilder_;
      /**
       * <code>.com.github.im.common.connect.model.proto.AckMessage ack = 4;</code>
       * @return Whether the ack field is set.
       */
      @java.lang.Override
      public boolean hasAck() {
        return payloadCase_ == 4;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AckMessage ack = 4;</code>
       * @return The ack.
       */
      @java.lang.Override
      public com.github.im.common.connect.model.proto.Chat.AckMessage getAck() {
        if (ackBuilder_ == null) {
          if (payloadCase_ == 4) {
            return (com.github.im.common.connect.model.proto.Chat.AckMessage) payload_;
          }
          return com.github.im.common.connect.model.proto.Chat.AckMessage.getDefaultInstance();
        } else {
          if (payloadCase_ == 4) {
            return ackBuilder_.getMessage();
          }
          return com.github.im.common.connect.model.proto.Chat.AckMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AckMessage ack = 4;</code>
       */
      public Builder setAck(com.github.im.common.connect.model.proto.Chat.AckMessage value) {
        if (ackBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          ackBuilder_.setMessage(value);
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AckMessage ack = 4;</code>
       */
      public Builder setAck(
          com.github.im.common.connect.model.proto.Chat.AckMessage.Builder builderForValue) {
        if (ackBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          ackBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AckMessage ack = 4;</code>
       */
      public Builder mergeAck(com.github.im.common.connect.model.proto.Chat.AckMessage value) {
        if (ackBuilder_ == null) {
          if (payloadCase_ == 4 &&
              payload_ != com.github.im.common.connect.model.proto.Chat.AckMessage.getDefaultInstance()) {
            payload_ = com.github.im.common.connect.model.proto.Chat.AckMessage.newBuilder((com.github.im.common.connect.model.proto.Chat.AckMessage) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 4) {
            ackBuilder_.mergeFrom(value);
          } else {
            ackBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AckMessage ack = 4;</code>
       */
      public Builder clearAck() {
        if (ackBuilder_ == null) {
          if (payloadCase_ == 4) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 4) {
            payloadCase_ = 0;
            payload_ = null;
          }
          ackBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AckMessage ack = 4;</code>
       */
      public com.github.im.common.connect.model.proto.Chat.AckMessage.Builder getAckBuilder() {
        return getAckFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AckMessage ack = 4;</code>
       */
      @java.lang.Override
      public com.github.im.common.connect.model.proto.Chat.AckMessageOrBuilder getAckOrBuilder() {
        if ((payloadCase_ == 4) && (ackBuilder_ != null)) {
          return ackBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 4) {
            return (com.github.im.common.connect.model.proto.Chat.AckMessage) payload_;
          }
          return com.github.im.common.connect.model.proto.Chat.AckMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AckMessage ack = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.github.im.common.connect.model.proto.Chat.AckMessage, com.github.im.common.connect.model.proto.Chat.AckMessage.Builder, com.github.im.common.connect.model.proto.Chat.AckMessageOrBuilder> 
          getAckFieldBuilder() {
        if (ackBuilder_ == null) {
          if (!(payloadCase_ == 4)) {
            payload_ = com.github.im.common.connect.model.proto.Chat.AckMessage.getDefaultInstance();
          }
          ackBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.github.im.common.connect.model.proto.Chat.AckMessage, com.github.im.common.connect.model.proto.Chat.AckMessage.Builder, com.github.im.common.connect.model.proto.Chat.AckMessageOrBuilder>(
                  (com.github.im.common.connect.model.proto.Chat.AckMessage) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 4;
        onChanged();
        return ackBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          com.github.im.common.connect.model.proto.BaseMessage.Heartbeat, com.github.im.common.connect.model.proto.BaseMessage.Heartbeat.Builder, com.github.im.common.connect.model.proto.BaseMessage.HeartbeatOrBuilder> heartbeatBuilder_;
      /**
       * <code>.com.github.im.common.connect.model.proto.Heartbeat heartbeat = 5;</code>
       * @return Whether the heartbeat field is set.
       */
      @java.lang.Override
      public boolean hasHeartbeat() {
        return payloadCase_ == 5;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.Heartbeat heartbeat = 5;</code>
       * @return The heartbeat.
       */
      @java.lang.Override
      public com.github.im.common.connect.model.proto.BaseMessage.Heartbeat getHeartbeat() {
        if (heartbeatBuilder_ == null) {
          if (payloadCase_ == 5) {
            return (com.github.im.common.connect.model.proto.BaseMessage.Heartbeat) payload_;
          }
          return com.github.im.common.connect.model.proto.BaseMessage.Heartbeat.getDefaultInstance();
        } else {
          if (payloadCase_ == 5) {
            return heartbeatBuilder_.getMessage();
          }
          return com.github.im.common.connect.model.proto.BaseMessage.Heartbeat.getDefaultInstance();
        }
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.Heartbeat heartbeat = 5;</code>
       */
      public Builder setHeartbeat(com.github.im.common.connect.model.proto.BaseMessage.Heartbeat value) {
        if (heartbeatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          heartbeatBuilder_.setMessage(value);
        }
        payloadCase_ = 5;
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.Heartbeat heartbeat = 5;</code>
       */
      public Builder setHeartbeat(
          com.github.im.common.connect.model.proto.BaseMessage.Heartbeat.Builder builderForValue) {
        if (heartbeatBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          heartbeatBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 5;
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.Heartbeat heartbeat = 5;</code>
       */
      public Builder mergeHeartbeat(com.github.im.common.connect.model.proto.BaseMessage.Heartbeat value) {
        if (heartbeatBuilder_ == null) {
          if (payloadCase_ == 5 &&
              payload_ != com.github.im.common.connect.model.proto.BaseMessage.Heartbeat.getDefaultInstance()) {
            payload_ = com.github.im.common.connect.model.proto.BaseMessage.Heartbeat.newBuilder((com.github.im.common.connect.model.proto.BaseMessage.Heartbeat) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 5) {
            heartbeatBuilder_.mergeFrom(value);
          } else {
            heartbeatBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 5;
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.Heartbeat heartbeat = 5;</code>
       */
      public Builder clearHeartbeat() {
        if (heartbeatBuilder_ == null) {
          if (payloadCase_ == 5) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 5) {
            payloadCase_ = 0;
            payload_ = null;
          }
          heartbeatBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.Heartbeat heartbeat = 5;</code>
       */
      public com.github.im.common.connect.model.proto.BaseMessage.Heartbeat.Builder getHeartbeatBuilder() {
        return getHeartbeatFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.Heartbeat heartbeat = 5;</code>
       */
      @java.lang.Override
      public com.github.im.common.connect.model.proto.BaseMessage.HeartbeatOrBuilder getHeartbeatOrBuilder() {
        if ((payloadCase_ == 5) && (heartbeatBuilder_ != null)) {
          return heartbeatBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 5) {
            return (com.github.im.common.connect.model.proto.BaseMessage.Heartbeat) payload_;
          }
          return com.github.im.common.connect.model.proto.BaseMessage.Heartbeat.getDefaultInstance();
        }
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.Heartbeat heartbeat = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.github.im.common.connect.model.proto.BaseMessage.Heartbeat, com.github.im.common.connect.model.proto.BaseMessage.Heartbeat.Builder, com.github.im.common.connect.model.proto.BaseMessage.HeartbeatOrBuilder> 
          getHeartbeatFieldBuilder() {
        if (heartbeatBuilder_ == null) {
          if (!(payloadCase_ == 5)) {
            payload_ = com.github.im.common.connect.model.proto.BaseMessage.Heartbeat.getDefaultInstance();
          }
          heartbeatBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.github.im.common.connect.model.proto.BaseMessage.Heartbeat, com.github.im.common.connect.model.proto.BaseMessage.Heartbeat.Builder, com.github.im.common.connect.model.proto.BaseMessage.HeartbeatOrBuilder>(
                  (com.github.im.common.connect.model.proto.BaseMessage.Heartbeat) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 5;
        onChanged();
        return heartbeatBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.github.im.common.connect.model.proto.BaseMessagePkg)
    }

    // @@protoc_insertion_point(class_scope:com.github.im.common.connect.model.proto.BaseMessagePkg)
    private static final com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg();
    }

    public static com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseMessagePkg>
        PARSER = new com.google.protobuf.AbstractParser<BaseMessagePkg>() {
      @java.lang.Override
      public BaseMessagePkg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<BaseMessagePkg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseMessagePkg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeartbeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.im.common.connect.model.proto.Heartbeat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * true 为 ping，false 为 pong
     * </pre>
     *
     * <code>bool ping = 1;</code>
     * @return The ping.
     */
    boolean getPing();
  }
  /**
   * Protobuf type {@code com.github.im.common.connect.model.proto.Heartbeat}
   */
  public static final class Heartbeat extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.github.im.common.connect.model.proto.Heartbeat)
      HeartbeatOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        Heartbeat.class.getName());
    }
    // Use Heartbeat.newBuilder() to construct.
    private Heartbeat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Heartbeat() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.im.common.connect.model.proto.BaseMessage.internal_static_com_github_im_common_connect_model_proto_Heartbeat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.im.common.connect.model.proto.BaseMessage.internal_static_com_github_im_common_connect_model_proto_Heartbeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.im.common.connect.model.proto.BaseMessage.Heartbeat.class, com.github.im.common.connect.model.proto.BaseMessage.Heartbeat.Builder.class);
    }

    public static final int PING_FIELD_NUMBER = 1;
    private boolean ping_ = false;
    /**
     * <pre>
     * true 为 ping，false 为 pong
     * </pre>
     *
     * <code>bool ping = 1;</code>
     * @return The ping.
     */
    @java.lang.Override
    public boolean getPing() {
      return ping_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ping_ != false) {
        output.writeBool(1, ping_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ping_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, ping_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.im.common.connect.model.proto.BaseMessage.Heartbeat)) {
        return super.equals(obj);
      }
      com.github.im.common.connect.model.proto.BaseMessage.Heartbeat other = (com.github.im.common.connect.model.proto.BaseMessage.Heartbeat) obj;

      if (getPing()
          != other.getPing()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPing());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.im.common.connect.model.proto.BaseMessage.Heartbeat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.Heartbeat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.Heartbeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.Heartbeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.Heartbeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.Heartbeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.Heartbeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.Heartbeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.im.common.connect.model.proto.BaseMessage.Heartbeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.im.common.connect.model.proto.BaseMessage.Heartbeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.Heartbeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.Heartbeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.im.common.connect.model.proto.BaseMessage.Heartbeat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.im.common.connect.model.proto.Heartbeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.im.common.connect.model.proto.Heartbeat)
        com.github.im.common.connect.model.proto.BaseMessage.HeartbeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.im.common.connect.model.proto.BaseMessage.internal_static_com_github_im_common_connect_model_proto_Heartbeat_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.im.common.connect.model.proto.BaseMessage.internal_static_com_github_im_common_connect_model_proto_Heartbeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.im.common.connect.model.proto.BaseMessage.Heartbeat.class, com.github.im.common.connect.model.proto.BaseMessage.Heartbeat.Builder.class);
      }

      // Construct using com.github.im.common.connect.model.proto.BaseMessage.Heartbeat.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        ping_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.im.common.connect.model.proto.BaseMessage.internal_static_com_github_im_common_connect_model_proto_Heartbeat_descriptor;
      }

      @java.lang.Override
      public com.github.im.common.connect.model.proto.BaseMessage.Heartbeat getDefaultInstanceForType() {
        return com.github.im.common.connect.model.proto.BaseMessage.Heartbeat.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.im.common.connect.model.proto.BaseMessage.Heartbeat build() {
        com.github.im.common.connect.model.proto.BaseMessage.Heartbeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.im.common.connect.model.proto.BaseMessage.Heartbeat buildPartial() {
        com.github.im.common.connect.model.proto.BaseMessage.Heartbeat result = new com.github.im.common.connect.model.proto.BaseMessage.Heartbeat(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.im.common.connect.model.proto.BaseMessage.Heartbeat result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.ping_ = ping_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.im.common.connect.model.proto.BaseMessage.Heartbeat) {
          return mergeFrom((com.github.im.common.connect.model.proto.BaseMessage.Heartbeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.im.common.connect.model.proto.BaseMessage.Heartbeat other) {
        if (other == com.github.im.common.connect.model.proto.BaseMessage.Heartbeat.getDefaultInstance()) return this;
        if (other.getPing() != false) {
          setPing(other.getPing());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                ping_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean ping_ ;
      /**
       * <pre>
       * true 为 ping，false 为 pong
       * </pre>
       *
       * <code>bool ping = 1;</code>
       * @return The ping.
       */
      @java.lang.Override
      public boolean getPing() {
        return ping_;
      }
      /**
       * <pre>
       * true 为 ping，false 为 pong
       * </pre>
       *
       * <code>bool ping = 1;</code>
       * @param value The ping to set.
       * @return This builder for chaining.
       */
      public Builder setPing(boolean value) {

        ping_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * true 为 ping，false 为 pong
       * </pre>
       *
       * <code>bool ping = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPing() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ping_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.github.im.common.connect.model.proto.Heartbeat)
    }

    // @@protoc_insertion_point(class_scope:com.github.im.common.connect.model.proto.Heartbeat)
    private static final com.github.im.common.connect.model.proto.BaseMessage.Heartbeat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.im.common.connect.model.proto.BaseMessage.Heartbeat();
    }

    public static com.github.im.common.connect.model.proto.BaseMessage.Heartbeat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Heartbeat>
        PARSER = new com.google.protobuf.AbstractParser<Heartbeat>() {
      @java.lang.Override
      public Heartbeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Heartbeat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Heartbeat> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.im.common.connect.model.proto.BaseMessage.Heartbeat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_im_common_connect_model_proto_BaseMessagePkg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_github_im_common_connect_model_proto_BaseMessagePkg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_im_common_connect_model_proto_Heartbeat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_github_im_common_connect_model_proto_Heartbeat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021BaseMessage.proto\022(com.github.im.commo" +
      "n.connect.model.proto\032\rAccount.proto\032\rMe" +
      "ssage.proto\032\022Notification.proto\"\226\003\n\016Base" +
      "MessagePkg\022L\n\013accountInfo\030\001 \001(\01325.com.gi" +
      "thub.im.common.connect.model.proto.Accou" +
      "ntInfoH\000\022H\n\007message\030\002 \001(\01325.com.github.i" +
      "m.common.connect.model.proto.ChatMessage" +
      "H\000\022R\n\014notification\030\003 \001(\0132:.com.github.im" +
      ".common.connect.model.proto.Notification" +
      "InfoH\000\022C\n\003ack\030\004 \001(\01324.com.github.im.comm" +
      "on.connect.model.proto.AckMessageH\000\022H\n\th" +
      "eartbeat\030\005 \001(\01323.com.github.im.common.co" +
      "nnect.model.proto.HeartbeatH\000B\t\n\007payload" +
      "\"\031\n\tHeartbeat\022\014\n\004ping\030\001 \001(\010B7\n(com.githu" +
      "b.im.common.connect.model.protoB\013BaseMes" +
      "sageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.im.common.connect.model.proto.Account.getDescriptor(),
          com.github.im.common.connect.model.proto.Chat.getDescriptor(),
          com.github.im.common.connect.model.proto.Notification.getDescriptor(),
        });
    internal_static_com_github_im_common_connect_model_proto_BaseMessagePkg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_im_common_connect_model_proto_BaseMessagePkg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_github_im_common_connect_model_proto_BaseMessagePkg_descriptor,
        new java.lang.String[] { "AccountInfo", "Message", "Notification", "Ack", "Heartbeat", "Payload", });
    internal_static_com_github_im_common_connect_model_proto_Heartbeat_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_github_im_common_connect_model_proto_Heartbeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_github_im_common_connect_model_proto_Heartbeat_descriptor,
        new java.lang.String[] { "Ping", });
    descriptor.resolveAllFeaturesImmutable();
    com.github.im.common.connect.model.proto.Account.getDescriptor();
    com.github.im.common.connect.model.proto.Chat.getDescriptor();
    com.github.im.common.connect.model.proto.Notification.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
