// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: BaseMessage.proto
// Protobuf Java Version: 4.28.2

package com.github.im.common.connect.model.proto;

public final class BaseMessage {
  private BaseMessage() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      BaseMessage.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BaseMessagePkgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.im.common.connect.model.proto.BaseMessagePkg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
     * @return Whether the accountInfo field is set.
     */
    boolean hasAccountInfo();
    /**
     * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
     * @return The accountInfo.
     */
    com.github.im.common.connect.model.proto.Account.AccountInfo getAccountInfo();
    /**
     * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
     */
    com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder getAccountInfoOrBuilder();

    /**
     * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
     * @return Whether the message field is set.
     */
    boolean hasMessage();
    /**
     * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
     * @return The message.
     */
    com.github.im.common.connect.model.proto.Chat.ChatMessage getMessage();
    /**
     * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
     */
    com.github.im.common.connect.model.proto.Chat.ChatMessageOrBuilder getMessageOrBuilder();

    com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg.PayloadCase getPayloadCase();
  }
  /**
   * Protobuf type {@code com.github.im.common.connect.model.proto.BaseMessagePkg}
   */
  public static final class BaseMessagePkg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.github.im.common.connect.model.proto.BaseMessagePkg)
      BaseMessagePkgOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        BaseMessagePkg.class.getName());
    }
    // Use BaseMessagePkg.newBuilder() to construct.
    private BaseMessagePkg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private BaseMessagePkg() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.im.common.connect.model.proto.BaseMessage.internal_static_com_github_im_common_connect_model_proto_BaseMessagePkg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.im.common.connect.model.proto.BaseMessage.internal_static_com_github_im_common_connect_model_proto_BaseMessagePkg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg.class, com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg.Builder.class);
    }

    private int payloadCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object payload_;
    public enum PayloadCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      ACCOUNTINFO(1),
      MESSAGE(2),
      PAYLOAD_NOT_SET(0);
      private final int value;
      private PayloadCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PayloadCase valueOf(int value) {
        return forNumber(value);
      }

      public static PayloadCase forNumber(int value) {
        switch (value) {
          case 1: return ACCOUNTINFO;
          case 2: return MESSAGE;
          case 0: return PAYLOAD_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PayloadCase
    getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public static final int ACCOUNTINFO_FIELD_NUMBER = 1;
    /**
     * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
     * @return Whether the accountInfo field is set.
     */
    @java.lang.Override
    public boolean hasAccountInfo() {
      return payloadCase_ == 1;
    }
    /**
     * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
     * @return The accountInfo.
     */
    @java.lang.Override
    public com.github.im.common.connect.model.proto.Account.AccountInfo getAccountInfo() {
      if (payloadCase_ == 1) {
         return (com.github.im.common.connect.model.proto.Account.AccountInfo) payload_;
      }
      return com.github.im.common.connect.model.proto.Account.AccountInfo.getDefaultInstance();
    }
    /**
     * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
     */
    @java.lang.Override
    public com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder getAccountInfoOrBuilder() {
      if (payloadCase_ == 1) {
         return (com.github.im.common.connect.model.proto.Account.AccountInfo) payload_;
      }
      return com.github.im.common.connect.model.proto.Account.AccountInfo.getDefaultInstance();
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    /**
     * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
     * @return Whether the message field is set.
     */
    @java.lang.Override
    public boolean hasMessage() {
      return payloadCase_ == 2;
    }
    /**
     * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public com.github.im.common.connect.model.proto.Chat.ChatMessage getMessage() {
      if (payloadCase_ == 2) {
         return (com.github.im.common.connect.model.proto.Chat.ChatMessage) payload_;
      }
      return com.github.im.common.connect.model.proto.Chat.ChatMessage.getDefaultInstance();
    }
    /**
     * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
     */
    @java.lang.Override
    public com.github.im.common.connect.model.proto.Chat.ChatMessageOrBuilder getMessageOrBuilder() {
      if (payloadCase_ == 2) {
         return (com.github.im.common.connect.model.proto.Chat.ChatMessage) payload_;
      }
      return com.github.im.common.connect.model.proto.Chat.ChatMessage.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (payloadCase_ == 1) {
        output.writeMessage(1, (com.github.im.common.connect.model.proto.Account.AccountInfo) payload_);
      }
      if (payloadCase_ == 2) {
        output.writeMessage(2, (com.github.im.common.connect.model.proto.Chat.ChatMessage) payload_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (payloadCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (com.github.im.common.connect.model.proto.Account.AccountInfo) payload_);
      }
      if (payloadCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.github.im.common.connect.model.proto.Chat.ChatMessage) payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg)) {
        return super.equals(obj);
      }
      com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg other = (com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg) obj;

      if (!getPayloadCase().equals(other.getPayloadCase())) return false;
      switch (payloadCase_) {
        case 1:
          if (!getAccountInfo()
              .equals(other.getAccountInfo())) return false;
          break;
        case 2:
          if (!getMessage()
              .equals(other.getMessage())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (payloadCase_) {
        case 1:
          hash = (37 * hash) + ACCOUNTINFO_FIELD_NUMBER;
          hash = (53 * hash) + getAccountInfo().hashCode();
          break;
        case 2:
          hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getMessage().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.im.common.connect.model.proto.BaseMessagePkg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.im.common.connect.model.proto.BaseMessagePkg)
        com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.im.common.connect.model.proto.BaseMessage.internal_static_com_github_im_common_connect_model_proto_BaseMessagePkg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.im.common.connect.model.proto.BaseMessage.internal_static_com_github_im_common_connect_model_proto_BaseMessagePkg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg.class, com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg.Builder.class);
      }

      // Construct using com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (accountInfoBuilder_ != null) {
          accountInfoBuilder_.clear();
        }
        if (messageBuilder_ != null) {
          messageBuilder_.clear();
        }
        payloadCase_ = 0;
        payload_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.im.common.connect.model.proto.BaseMessage.internal_static_com_github_im_common_connect_model_proto_BaseMessagePkg_descriptor;
      }

      @java.lang.Override
      public com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg getDefaultInstanceForType() {
        return com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg build() {
        com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg buildPartial() {
        com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg result = new com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg result) {
        int from_bitField0_ = bitField0_;
      }

      private void buildPartialOneofs(com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg result) {
        result.payloadCase_ = payloadCase_;
        result.payload_ = this.payload_;
        if (payloadCase_ == 1 &&
            accountInfoBuilder_ != null) {
          result.payload_ = accountInfoBuilder_.build();
        }
        if (payloadCase_ == 2 &&
            messageBuilder_ != null) {
          result.payload_ = messageBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg) {
          return mergeFrom((com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg other) {
        if (other == com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg.getDefaultInstance()) return this;
        switch (other.getPayloadCase()) {
          case ACCOUNTINFO: {
            mergeAccountInfo(other.getAccountInfo());
            break;
          }
          case MESSAGE: {
            mergeMessage(other.getMessage());
            break;
          }
          case PAYLOAD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getAccountInfoFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 1;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getMessageFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 2;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int payloadCase_ = 0;
      private java.lang.Object payload_;
      public PayloadCase
          getPayloadCase() {
        return PayloadCase.forNumber(
            payloadCase_);
      }

      public Builder clearPayload() {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilder<
          com.github.im.common.connect.model.proto.Account.AccountInfo, com.github.im.common.connect.model.proto.Account.AccountInfo.Builder, com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder> accountInfoBuilder_;
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
       * @return Whether the accountInfo field is set.
       */
      @java.lang.Override
      public boolean hasAccountInfo() {
        return payloadCase_ == 1;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
       * @return The accountInfo.
       */
      @java.lang.Override
      public com.github.im.common.connect.model.proto.Account.AccountInfo getAccountInfo() {
        if (accountInfoBuilder_ == null) {
          if (payloadCase_ == 1) {
            return (com.github.im.common.connect.model.proto.Account.AccountInfo) payload_;
          }
          return com.github.im.common.connect.model.proto.Account.AccountInfo.getDefaultInstance();
        } else {
          if (payloadCase_ == 1) {
            return accountInfoBuilder_.getMessage();
          }
          return com.github.im.common.connect.model.proto.Account.AccountInfo.getDefaultInstance();
        }
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
       */
      public Builder setAccountInfo(com.github.im.common.connect.model.proto.Account.AccountInfo value) {
        if (accountInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          accountInfoBuilder_.setMessage(value);
        }
        payloadCase_ = 1;
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
       */
      public Builder setAccountInfo(
          com.github.im.common.connect.model.proto.Account.AccountInfo.Builder builderForValue) {
        if (accountInfoBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          accountInfoBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 1;
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
       */
      public Builder mergeAccountInfo(com.github.im.common.connect.model.proto.Account.AccountInfo value) {
        if (accountInfoBuilder_ == null) {
          if (payloadCase_ == 1 &&
              payload_ != com.github.im.common.connect.model.proto.Account.AccountInfo.getDefaultInstance()) {
            payload_ = com.github.im.common.connect.model.proto.Account.AccountInfo.newBuilder((com.github.im.common.connect.model.proto.Account.AccountInfo) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 1) {
            accountInfoBuilder_.mergeFrom(value);
          } else {
            accountInfoBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 1;
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
       */
      public Builder clearAccountInfo() {
        if (accountInfoBuilder_ == null) {
          if (payloadCase_ == 1) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 1) {
            payloadCase_ = 0;
            payload_ = null;
          }
          accountInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
       */
      public com.github.im.common.connect.model.proto.Account.AccountInfo.Builder getAccountInfoBuilder() {
        return getAccountInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
       */
      @java.lang.Override
      public com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder getAccountInfoOrBuilder() {
        if ((payloadCase_ == 1) && (accountInfoBuilder_ != null)) {
          return accountInfoBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 1) {
            return (com.github.im.common.connect.model.proto.Account.AccountInfo) payload_;
          }
          return com.github.im.common.connect.model.proto.Account.AccountInfo.getDefaultInstance();
        }
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo accountInfo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.github.im.common.connect.model.proto.Account.AccountInfo, com.github.im.common.connect.model.proto.Account.AccountInfo.Builder, com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder> 
          getAccountInfoFieldBuilder() {
        if (accountInfoBuilder_ == null) {
          if (!(payloadCase_ == 1)) {
            payload_ = com.github.im.common.connect.model.proto.Account.AccountInfo.getDefaultInstance();
          }
          accountInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.github.im.common.connect.model.proto.Account.AccountInfo, com.github.im.common.connect.model.proto.Account.AccountInfo.Builder, com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder>(
                  (com.github.im.common.connect.model.proto.Account.AccountInfo) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 1;
        onChanged();
        return accountInfoBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          com.github.im.common.connect.model.proto.Chat.ChatMessage, com.github.im.common.connect.model.proto.Chat.ChatMessage.Builder, com.github.im.common.connect.model.proto.Chat.ChatMessageOrBuilder> messageBuilder_;
      /**
       * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
       * @return Whether the message field is set.
       */
      @java.lang.Override
      public boolean hasMessage() {
        return payloadCase_ == 2;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
       * @return The message.
       */
      @java.lang.Override
      public com.github.im.common.connect.model.proto.Chat.ChatMessage getMessage() {
        if (messageBuilder_ == null) {
          if (payloadCase_ == 2) {
            return (com.github.im.common.connect.model.proto.Chat.ChatMessage) payload_;
          }
          return com.github.im.common.connect.model.proto.Chat.ChatMessage.getDefaultInstance();
        } else {
          if (payloadCase_ == 2) {
            return messageBuilder_.getMessage();
          }
          return com.github.im.common.connect.model.proto.Chat.ChatMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
       */
      public Builder setMessage(com.github.im.common.connect.model.proto.Chat.ChatMessage value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          messageBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
       */
      public Builder setMessage(
          com.github.im.common.connect.model.proto.Chat.ChatMessage.Builder builderForValue) {
        if (messageBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          messageBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
       */
      public Builder mergeMessage(com.github.im.common.connect.model.proto.Chat.ChatMessage value) {
        if (messageBuilder_ == null) {
          if (payloadCase_ == 2 &&
              payload_ != com.github.im.common.connect.model.proto.Chat.ChatMessage.getDefaultInstance()) {
            payload_ = com.github.im.common.connect.model.proto.Chat.ChatMessage.newBuilder((com.github.im.common.connect.model.proto.Chat.ChatMessage) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 2) {
            messageBuilder_.mergeFrom(value);
          } else {
            messageBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
       */
      public Builder clearMessage() {
        if (messageBuilder_ == null) {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
          }
          messageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
       */
      public com.github.im.common.connect.model.proto.Chat.ChatMessage.Builder getMessageBuilder() {
        return getMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
       */
      @java.lang.Override
      public com.github.im.common.connect.model.proto.Chat.ChatMessageOrBuilder getMessageOrBuilder() {
        if ((payloadCase_ == 2) && (messageBuilder_ != null)) {
          return messageBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 2) {
            return (com.github.im.common.connect.model.proto.Chat.ChatMessage) payload_;
          }
          return com.github.im.common.connect.model.proto.Chat.ChatMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.ChatMessage message = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.github.im.common.connect.model.proto.Chat.ChatMessage, com.github.im.common.connect.model.proto.Chat.ChatMessage.Builder, com.github.im.common.connect.model.proto.Chat.ChatMessageOrBuilder> 
          getMessageFieldBuilder() {
        if (messageBuilder_ == null) {
          if (!(payloadCase_ == 2)) {
            payload_ = com.github.im.common.connect.model.proto.Chat.ChatMessage.getDefaultInstance();
          }
          messageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.github.im.common.connect.model.proto.Chat.ChatMessage, com.github.im.common.connect.model.proto.Chat.ChatMessage.Builder, com.github.im.common.connect.model.proto.Chat.ChatMessageOrBuilder>(
                  (com.github.im.common.connect.model.proto.Chat.ChatMessage) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 2;
        onChanged();
        return messageBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.github.im.common.connect.model.proto.BaseMessagePkg)
    }

    // @@protoc_insertion_point(class_scope:com.github.im.common.connect.model.proto.BaseMessagePkg)
    private static final com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg();
    }

    public static com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseMessagePkg>
        PARSER = new com.google.protobuf.AbstractParser<BaseMessagePkg>() {
      @java.lang.Override
      public BaseMessagePkg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<BaseMessagePkg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseMessagePkg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.im.common.connect.model.proto.BaseMessage.BaseMessagePkg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_im_common_connect_model_proto_BaseMessagePkg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_github_im_common_connect_model_proto_BaseMessagePkg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021BaseMessage.proto\022(com.github.im.commo" +
      "n.connect.model.proto\032\rAccount.proto\032\rMe" +
      "ssage.proto\"\263\001\n\016BaseMessagePkg\022L\n\013accoun" +
      "tInfo\030\001 \001(\01325.com.github.im.common.conne" +
      "ct.model.proto.AccountInfoH\000\022H\n\007message\030" +
      "\002 \001(\01325.com.github.im.common.connect.mod" +
      "el.proto.ChatMessageH\000B\t\n\007payloadB7\n(com" +
      ".github.im.common.connect.model.protoB\013B" +
      "aseMessageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.im.common.connect.model.proto.Account.getDescriptor(),
          com.github.im.common.connect.model.proto.Chat.getDescriptor(),
        });
    internal_static_com_github_im_common_connect_model_proto_BaseMessagePkg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_im_common_connect_model_proto_BaseMessagePkg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_github_im_common_connect_model_proto_BaseMessagePkg_descriptor,
        new java.lang.String[] { "AccountInfo", "Message", "Payload", });
    descriptor.resolveAllFeaturesImmutable();
    com.github.im.common.connect.model.proto.Account.getDescriptor();
    com.github.im.common.connect.model.proto.Chat.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
