// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Message.proto
// Protobuf Java Version: 4.28.2

package com.github.im.common.connect.model.proto;

public final class Chat {
  private Chat() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      Chat.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.github.im.common.connect.model.proto.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TEXT = 0;</code>
     */
    TEXT(0),
    /**
     * <code>MARKDOWN = 5;</code>
     */
    MARKDOWN(5),
    /**
     * <code>FILE = 1;</code>
     */
    FILE(1),
    /**
     * <code>STREAM = 2;</code>
     */
    STREAM(2),
    /**
     * <code>VIDEO = 3;</code>
     */
    VIDEO(3),
    /**
     * <code>IMAGE = 6;</code>
     */
    IMAGE(6),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        MessageType.class.getName());
    }
    /**
     * <code>TEXT = 0;</code>
     */
    public static final int TEXT_VALUE = 0;
    /**
     * <code>MARKDOWN = 5;</code>
     */
    public static final int MARKDOWN_VALUE = 5;
    /**
     * <code>FILE = 1;</code>
     */
    public static final int FILE_VALUE = 1;
    /**
     * <code>STREAM = 2;</code>
     */
    public static final int STREAM_VALUE = 2;
    /**
     * <code>VIDEO = 3;</code>
     */
    public static final int VIDEO_VALUE = 3;
    /**
     * <code>IMAGE = 6;</code>
     */
    public static final int IMAGE_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return TEXT;
        case 5: return MARKDOWN;
        case 1: return FILE;
        case 2: return STREAM;
        case 3: return VIDEO;
        case 6: return IMAGE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.im.common.connect.model.proto.Chat.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.github.im.common.connect.model.proto.MessageType)
  }

  public interface ChatMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.im.common.connect.model.proto.ChatMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 msgId = 1;</code>
     * @return The msgId.
     */
    long getMsgId();

    /**
     * <code>string content = 3;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * client-server
     * </pre>
     *
     * <code>int64 conversationId = 9;</code>
     * @return The conversationId.
     */
    long getConversationId();

    /**
     * <code>string conversationName = 10;</code>
     * @return The conversationName.
     */
    java.lang.String getConversationName();
    /**
     * <code>string conversationName = 10;</code>
     * @return The bytes for conversationName.
     */
    com.google.protobuf.ByteString
        getConversationNameBytes();

    /**
     * <code>.com.github.im.common.connect.model.proto.AccountInfo fromAccountInfo = 2;</code>
     * @return Whether the fromAccountInfo field is set.
     */
    boolean hasFromAccountInfo();
    /**
     * <code>.com.github.im.common.connect.model.proto.AccountInfo fromAccountInfo = 2;</code>
     * @return The fromAccountInfo.
     */
    com.github.im.common.connect.model.proto.Account.AccountInfo getFromAccountInfo();
    /**
     * <code>.com.github.im.common.connect.model.proto.AccountInfo fromAccountInfo = 2;</code>
     */
    com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder getFromAccountInfoOrBuilder();

    /**
     * <pre>
     * server-client 需要使用 用于指示推送到的客户端
     * </pre>
     *
     * <code>.com.github.im.common.connect.model.proto.AccountInfo toAccountInfo = 8;</code>
     * @return Whether the toAccountInfo field is set.
     */
    boolean hasToAccountInfo();
    /**
     * <pre>
     * server-client 需要使用 用于指示推送到的客户端
     * </pre>
     *
     * <code>.com.github.im.common.connect.model.proto.AccountInfo toAccountInfo = 8;</code>
     * @return The toAccountInfo.
     */
    com.github.im.common.connect.model.proto.Account.AccountInfo getToAccountInfo();
    /**
     * <pre>
     * server-client 需要使用 用于指示推送到的客户端
     * </pre>
     *
     * <code>.com.github.im.common.connect.model.proto.AccountInfo toAccountInfo = 8;</code>
     */
    com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder getToAccountInfoOrBuilder();

    /**
     * <code>sint32 clientTimeStamp = 7;</code>
     * @return The clientTimeStamp.
     */
    int getClientTimeStamp();

    /**
     * <code>sint32 serverTimeStamp = 12;</code>
     * @return The serverTimeStamp.
     */
    int getServerTimeStamp();

    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.com.github.im.common.connect.model.proto.MessageType type = 6;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.com.github.im.common.connect.model.proto.MessageType type = 6;</code>
     * @return The type.
     */
    com.github.im.common.connect.model.proto.Chat.MessageType getType();

    /**
     * <pre>
     * 消息状态
     * </pre>
     *
     * <code>.com.github.im.common.connect.model.proto.ChatMessage.MessagesStatus messagesStatus = 11;</code>
     * @return The enum numeric value on the wire for messagesStatus.
     */
    int getMessagesStatusValue();
    /**
     * <pre>
     * 消息状态
     * </pre>
     *
     * <code>.com.github.im.common.connect.model.proto.ChatMessage.MessagesStatus messagesStatus = 11;</code>
     * @return The messagesStatus.
     */
    com.github.im.common.connect.model.proto.Chat.ChatMessage.MessagesStatus getMessagesStatus();

    /**
     * <pre>
     * generateBy server
     * </pre>
     *
     * <code>int64 sequenceId = 5;</code>
     * @return The sequenceId.
     */
    long getSequenceId();
  }
  /**
   * <pre>
   * chat 信息
   * </pre>
   *
   * Protobuf type {@code com.github.im.common.connect.model.proto.ChatMessage}
   */
  public static final class ChatMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.github.im.common.connect.model.proto.ChatMessage)
      ChatMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        ChatMessage.class.getName());
    }
    // Use ChatMessage.newBuilder() to construct.
    private ChatMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ChatMessage() {
      content_ = "";
      conversationName_ = "";
      type_ = 0;
      messagesStatus_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.im.common.connect.model.proto.Chat.internal_static_com_github_im_common_connect_model_proto_ChatMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.im.common.connect.model.proto.Chat.internal_static_com_github_im_common_connect_model_proto_ChatMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.im.common.connect.model.proto.Chat.ChatMessage.class, com.github.im.common.connect.model.proto.Chat.ChatMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code com.github.im.common.connect.model.proto.ChatMessage.MessagesStatus}
     */
    public enum MessagesStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>REJECT = 0;</code>
       */
      REJECT(0),
      /**
       * <code>OFFLINE = 1;</code>
       */
      OFFLINE(1),
      /**
       * <code>SENTFAIL = 7;</code>
       */
      SENTFAIL(7),
      /**
       * <code>HISTORY = 10;</code>
       */
      HISTORY(10),
      /**
       * <code>READ = 3;</code>
       */
      READ(3),
      /**
       * <code>UNREAD = 2;</code>
       */
      UNREAD(2),
      /**
       * <code>SENT = 5;</code>
       */
      SENT(5),
      /**
       * <pre>
       * 用于客户端标识发送状态
       * </pre>
       *
       * <code>UNSENT = 11;</code>
       */
      UNSENT(11),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 28,
          /* patch= */ 2,
          /* suffix= */ "",
          MessagesStatus.class.getName());
      }
      /**
       * <code>REJECT = 0;</code>
       */
      public static final int REJECT_VALUE = 0;
      /**
       * <code>OFFLINE = 1;</code>
       */
      public static final int OFFLINE_VALUE = 1;
      /**
       * <code>SENTFAIL = 7;</code>
       */
      public static final int SENTFAIL_VALUE = 7;
      /**
       * <code>HISTORY = 10;</code>
       */
      public static final int HISTORY_VALUE = 10;
      /**
       * <code>READ = 3;</code>
       */
      public static final int READ_VALUE = 3;
      /**
       * <code>UNREAD = 2;</code>
       */
      public static final int UNREAD_VALUE = 2;
      /**
       * <code>SENT = 5;</code>
       */
      public static final int SENT_VALUE = 5;
      /**
       * <pre>
       * 用于客户端标识发送状态
       * </pre>
       *
       * <code>UNSENT = 11;</code>
       */
      public static final int UNSENT_VALUE = 11;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessagesStatus valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static MessagesStatus forNumber(int value) {
        switch (value) {
          case 0: return REJECT;
          case 1: return OFFLINE;
          case 7: return SENTFAIL;
          case 10: return HISTORY;
          case 3: return READ;
          case 2: return UNREAD;
          case 5: return SENT;
          case 11: return UNSENT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessagesStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessagesStatus> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessagesStatus>() {
              public MessagesStatus findValueByNumber(int number) {
                return MessagesStatus.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.github.im.common.connect.model.proto.Chat.ChatMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessagesStatus[] VALUES = values();

      public static MessagesStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessagesStatus(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.github.im.common.connect.model.proto.ChatMessage.MessagesStatus)
    }

    private int bitField0_;
    public static final int MSGID_FIELD_NUMBER = 1;
    private long msgId_ = 0L;
    /**
     * <code>int64 msgId = 1;</code>
     * @return The msgId.
     */
    @java.lang.Override
    public long getMsgId() {
      return msgId_;
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object content_ = "";
    /**
     * <code>string content = 3;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONVERSATIONID_FIELD_NUMBER = 9;
    private long conversationId_ = 0L;
    /**
     * <pre>
     * client-server
     * </pre>
     *
     * <code>int64 conversationId = 9;</code>
     * @return The conversationId.
     */
    @java.lang.Override
    public long getConversationId() {
      return conversationId_;
    }

    public static final int CONVERSATIONNAME_FIELD_NUMBER = 10;
    @SuppressWarnings("serial")
    private volatile java.lang.Object conversationName_ = "";
    /**
     * <code>string conversationName = 10;</code>
     * @return The conversationName.
     */
    @java.lang.Override
    public java.lang.String getConversationName() {
      java.lang.Object ref = conversationName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        conversationName_ = s;
        return s;
      }
    }
    /**
     * <code>string conversationName = 10;</code>
     * @return The bytes for conversationName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConversationNameBytes() {
      java.lang.Object ref = conversationName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        conversationName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROMACCOUNTINFO_FIELD_NUMBER = 2;
    private com.github.im.common.connect.model.proto.Account.AccountInfo fromAccountInfo_;
    /**
     * <code>.com.github.im.common.connect.model.proto.AccountInfo fromAccountInfo = 2;</code>
     * @return Whether the fromAccountInfo field is set.
     */
    @java.lang.Override
    public boolean hasFromAccountInfo() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.com.github.im.common.connect.model.proto.AccountInfo fromAccountInfo = 2;</code>
     * @return The fromAccountInfo.
     */
    @java.lang.Override
    public com.github.im.common.connect.model.proto.Account.AccountInfo getFromAccountInfo() {
      return fromAccountInfo_ == null ? com.github.im.common.connect.model.proto.Account.AccountInfo.getDefaultInstance() : fromAccountInfo_;
    }
    /**
     * <code>.com.github.im.common.connect.model.proto.AccountInfo fromAccountInfo = 2;</code>
     */
    @java.lang.Override
    public com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder getFromAccountInfoOrBuilder() {
      return fromAccountInfo_ == null ? com.github.im.common.connect.model.proto.Account.AccountInfo.getDefaultInstance() : fromAccountInfo_;
    }

    public static final int TOACCOUNTINFO_FIELD_NUMBER = 8;
    private com.github.im.common.connect.model.proto.Account.AccountInfo toAccountInfo_;
    /**
     * <pre>
     * server-client 需要使用 用于指示推送到的客户端
     * </pre>
     *
     * <code>.com.github.im.common.connect.model.proto.AccountInfo toAccountInfo = 8;</code>
     * @return Whether the toAccountInfo field is set.
     */
    @java.lang.Override
    public boolean hasToAccountInfo() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * server-client 需要使用 用于指示推送到的客户端
     * </pre>
     *
     * <code>.com.github.im.common.connect.model.proto.AccountInfo toAccountInfo = 8;</code>
     * @return The toAccountInfo.
     */
    @java.lang.Override
    public com.github.im.common.connect.model.proto.Account.AccountInfo getToAccountInfo() {
      return toAccountInfo_ == null ? com.github.im.common.connect.model.proto.Account.AccountInfo.getDefaultInstance() : toAccountInfo_;
    }
    /**
     * <pre>
     * server-client 需要使用 用于指示推送到的客户端
     * </pre>
     *
     * <code>.com.github.im.common.connect.model.proto.AccountInfo toAccountInfo = 8;</code>
     */
    @java.lang.Override
    public com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder getToAccountInfoOrBuilder() {
      return toAccountInfo_ == null ? com.github.im.common.connect.model.proto.Account.AccountInfo.getDefaultInstance() : toAccountInfo_;
    }

    public static final int CLIENTTIMESTAMP_FIELD_NUMBER = 7;
    private int clientTimeStamp_ = 0;
    /**
     * <code>sint32 clientTimeStamp = 7;</code>
     * @return The clientTimeStamp.
     */
    @java.lang.Override
    public int getClientTimeStamp() {
      return clientTimeStamp_;
    }

    public static final int SERVERTIMESTAMP_FIELD_NUMBER = 12;
    private int serverTimeStamp_ = 0;
    /**
     * <code>sint32 serverTimeStamp = 12;</code>
     * @return The serverTimeStamp.
     */
    @java.lang.Override
    public int getServerTimeStamp() {
      return serverTimeStamp_;
    }

    public static final int TYPE_FIELD_NUMBER = 6;
    private int type_ = 0;
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.com.github.im.common.connect.model.proto.MessageType type = 6;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.com.github.im.common.connect.model.proto.MessageType type = 6;</code>
     * @return The type.
     */
    @java.lang.Override public com.github.im.common.connect.model.proto.Chat.MessageType getType() {
      com.github.im.common.connect.model.proto.Chat.MessageType result = com.github.im.common.connect.model.proto.Chat.MessageType.forNumber(type_);
      return result == null ? com.github.im.common.connect.model.proto.Chat.MessageType.UNRECOGNIZED : result;
    }

    public static final int MESSAGESSTATUS_FIELD_NUMBER = 11;
    private int messagesStatus_ = 0;
    /**
     * <pre>
     * 消息状态
     * </pre>
     *
     * <code>.com.github.im.common.connect.model.proto.ChatMessage.MessagesStatus messagesStatus = 11;</code>
     * @return The enum numeric value on the wire for messagesStatus.
     */
    @java.lang.Override public int getMessagesStatusValue() {
      return messagesStatus_;
    }
    /**
     * <pre>
     * 消息状态
     * </pre>
     *
     * <code>.com.github.im.common.connect.model.proto.ChatMessage.MessagesStatus messagesStatus = 11;</code>
     * @return The messagesStatus.
     */
    @java.lang.Override public com.github.im.common.connect.model.proto.Chat.ChatMessage.MessagesStatus getMessagesStatus() {
      com.github.im.common.connect.model.proto.Chat.ChatMessage.MessagesStatus result = com.github.im.common.connect.model.proto.Chat.ChatMessage.MessagesStatus.forNumber(messagesStatus_);
      return result == null ? com.github.im.common.connect.model.proto.Chat.ChatMessage.MessagesStatus.UNRECOGNIZED : result;
    }

    public static final int SEQUENCEID_FIELD_NUMBER = 5;
    private long sequenceId_ = 0L;
    /**
     * <pre>
     * generateBy server
     * </pre>
     *
     * <code>int64 sequenceId = 5;</code>
     * @return The sequenceId.
     */
    @java.lang.Override
    public long getSequenceId() {
      return sequenceId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgId_ != 0L) {
        output.writeInt64(1, msgId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getFromAccountInfo());
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(content_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, content_);
      }
      if (sequenceId_ != 0L) {
        output.writeInt64(5, sequenceId_);
      }
      if (type_ != com.github.im.common.connect.model.proto.Chat.MessageType.TEXT.getNumber()) {
        output.writeEnum(6, type_);
      }
      if (clientTimeStamp_ != 0) {
        output.writeSInt32(7, clientTimeStamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(8, getToAccountInfo());
      }
      if (conversationId_ != 0L) {
        output.writeInt64(9, conversationId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(conversationName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 10, conversationName_);
      }
      if (messagesStatus_ != com.github.im.common.connect.model.proto.Chat.ChatMessage.MessagesStatus.REJECT.getNumber()) {
        output.writeEnum(11, messagesStatus_);
      }
      if (serverTimeStamp_ != 0) {
        output.writeSInt32(12, serverTimeStamp_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, msgId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getFromAccountInfo());
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(content_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, content_);
      }
      if (sequenceId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, sequenceId_);
      }
      if (type_ != com.github.im.common.connect.model.proto.Chat.MessageType.TEXT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, type_);
      }
      if (clientTimeStamp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(7, clientTimeStamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getToAccountInfo());
      }
      if (conversationId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, conversationId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(conversationName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(10, conversationName_);
      }
      if (messagesStatus_ != com.github.im.common.connect.model.proto.Chat.ChatMessage.MessagesStatus.REJECT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(11, messagesStatus_);
      }
      if (serverTimeStamp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(12, serverTimeStamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.im.common.connect.model.proto.Chat.ChatMessage)) {
        return super.equals(obj);
      }
      com.github.im.common.connect.model.proto.Chat.ChatMessage other = (com.github.im.common.connect.model.proto.Chat.ChatMessage) obj;

      if (getMsgId()
          != other.getMsgId()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (getConversationId()
          != other.getConversationId()) return false;
      if (!getConversationName()
          .equals(other.getConversationName())) return false;
      if (hasFromAccountInfo() != other.hasFromAccountInfo()) return false;
      if (hasFromAccountInfo()) {
        if (!getFromAccountInfo()
            .equals(other.getFromAccountInfo())) return false;
      }
      if (hasToAccountInfo() != other.hasToAccountInfo()) return false;
      if (hasToAccountInfo()) {
        if (!getToAccountInfo()
            .equals(other.getToAccountInfo())) return false;
      }
      if (getClientTimeStamp()
          != other.getClientTimeStamp()) return false;
      if (getServerTimeStamp()
          != other.getServerTimeStamp()) return false;
      if (type_ != other.type_) return false;
      if (messagesStatus_ != other.messagesStatus_) return false;
      if (getSequenceId()
          != other.getSequenceId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgId());
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + CONVERSATIONID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getConversationId());
      hash = (37 * hash) + CONVERSATIONNAME_FIELD_NUMBER;
      hash = (53 * hash) + getConversationName().hashCode();
      if (hasFromAccountInfo()) {
        hash = (37 * hash) + FROMACCOUNTINFO_FIELD_NUMBER;
        hash = (53 * hash) + getFromAccountInfo().hashCode();
      }
      if (hasToAccountInfo()) {
        hash = (37 * hash) + TOACCOUNTINFO_FIELD_NUMBER;
        hash = (53 * hash) + getToAccountInfo().hashCode();
      }
      hash = (37 * hash) + CLIENTTIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getClientTimeStamp();
      hash = (37 * hash) + SERVERTIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getServerTimeStamp();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + MESSAGESSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + messagesStatus_;
      hash = (37 * hash) + SEQUENCEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSequenceId());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.im.common.connect.model.proto.Chat.ChatMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.im.common.connect.model.proto.Chat.ChatMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.Chat.ChatMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.im.common.connect.model.proto.Chat.ChatMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.Chat.ChatMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.im.common.connect.model.proto.Chat.ChatMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.Chat.ChatMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.im.common.connect.model.proto.Chat.ChatMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.im.common.connect.model.proto.Chat.ChatMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.im.common.connect.model.proto.Chat.ChatMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.Chat.ChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.im.common.connect.model.proto.Chat.ChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.im.common.connect.model.proto.Chat.ChatMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * chat 信息
     * </pre>
     *
     * Protobuf type {@code com.github.im.common.connect.model.proto.ChatMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.im.common.connect.model.proto.ChatMessage)
        com.github.im.common.connect.model.proto.Chat.ChatMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.im.common.connect.model.proto.Chat.internal_static_com_github_im_common_connect_model_proto_ChatMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.im.common.connect.model.proto.Chat.internal_static_com_github_im_common_connect_model_proto_ChatMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.im.common.connect.model.proto.Chat.ChatMessage.class, com.github.im.common.connect.model.proto.Chat.ChatMessage.Builder.class);
      }

      // Construct using com.github.im.common.connect.model.proto.Chat.ChatMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getFromAccountInfoFieldBuilder();
          getToAccountInfoFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        msgId_ = 0L;
        content_ = "";
        conversationId_ = 0L;
        conversationName_ = "";
        fromAccountInfo_ = null;
        if (fromAccountInfoBuilder_ != null) {
          fromAccountInfoBuilder_.dispose();
          fromAccountInfoBuilder_ = null;
        }
        toAccountInfo_ = null;
        if (toAccountInfoBuilder_ != null) {
          toAccountInfoBuilder_.dispose();
          toAccountInfoBuilder_ = null;
        }
        clientTimeStamp_ = 0;
        serverTimeStamp_ = 0;
        type_ = 0;
        messagesStatus_ = 0;
        sequenceId_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.im.common.connect.model.proto.Chat.internal_static_com_github_im_common_connect_model_proto_ChatMessage_descriptor;
      }

      @java.lang.Override
      public com.github.im.common.connect.model.proto.Chat.ChatMessage getDefaultInstanceForType() {
        return com.github.im.common.connect.model.proto.Chat.ChatMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.im.common.connect.model.proto.Chat.ChatMessage build() {
        com.github.im.common.connect.model.proto.Chat.ChatMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.im.common.connect.model.proto.Chat.ChatMessage buildPartial() {
        com.github.im.common.connect.model.proto.Chat.ChatMessage result = new com.github.im.common.connect.model.proto.Chat.ChatMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.im.common.connect.model.proto.Chat.ChatMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.msgId_ = msgId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.content_ = content_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.conversationId_ = conversationId_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.conversationName_ = conversationName_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.fromAccountInfo_ = fromAccountInfoBuilder_ == null
              ? fromAccountInfo_
              : fromAccountInfoBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.toAccountInfo_ = toAccountInfoBuilder_ == null
              ? toAccountInfo_
              : toAccountInfoBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.clientTimeStamp_ = clientTimeStamp_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.serverTimeStamp_ = serverTimeStamp_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.messagesStatus_ = messagesStatus_;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.sequenceId_ = sequenceId_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.im.common.connect.model.proto.Chat.ChatMessage) {
          return mergeFrom((com.github.im.common.connect.model.proto.Chat.ChatMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.im.common.connect.model.proto.Chat.ChatMessage other) {
        if (other == com.github.im.common.connect.model.proto.Chat.ChatMessage.getDefaultInstance()) return this;
        if (other.getMsgId() != 0L) {
          setMsgId(other.getMsgId());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getConversationId() != 0L) {
          setConversationId(other.getConversationId());
        }
        if (!other.getConversationName().isEmpty()) {
          conversationName_ = other.conversationName_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.hasFromAccountInfo()) {
          mergeFromAccountInfo(other.getFromAccountInfo());
        }
        if (other.hasToAccountInfo()) {
          mergeToAccountInfo(other.getToAccountInfo());
        }
        if (other.getClientTimeStamp() != 0) {
          setClientTimeStamp(other.getClientTimeStamp());
        }
        if (other.getServerTimeStamp() != 0) {
          setServerTimeStamp(other.getServerTimeStamp());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.messagesStatus_ != 0) {
          setMessagesStatusValue(other.getMessagesStatusValue());
        }
        if (other.getSequenceId() != 0L) {
          setSequenceId(other.getSequenceId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                msgId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getFromAccountInfoFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 18
              case 26: {
                content_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 26
              case 40: {
                sequenceId_ = input.readInt64();
                bitField0_ |= 0x00000400;
                break;
              } // case 40
              case 48: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000100;
                break;
              } // case 48
              case 56: {
                clientTimeStamp_ = input.readSInt32();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 66: {
                input.readMessage(
                    getToAccountInfoFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000020;
                break;
              } // case 66
              case 72: {
                conversationId_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 72
              case 82: {
                conversationName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 82
              case 88: {
                messagesStatus_ = input.readEnum();
                bitField0_ |= 0x00000200;
                break;
              } // case 88
              case 96: {
                serverTimeStamp_ = input.readSInt32();
                bitField0_ |= 0x00000080;
                break;
              } // case 96
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long msgId_ ;
      /**
       * <code>int64 msgId = 1;</code>
       * @return The msgId.
       */
      @java.lang.Override
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <code>int64 msgId = 1;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(long value) {

        msgId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 msgId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 3;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        content_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        content_ = getDefaultInstance().getContent();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        content_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long conversationId_ ;
      /**
       * <pre>
       * client-server
       * </pre>
       *
       * <code>int64 conversationId = 9;</code>
       * @return The conversationId.
       */
      @java.lang.Override
      public long getConversationId() {
        return conversationId_;
      }
      /**
       * <pre>
       * client-server
       * </pre>
       *
       * <code>int64 conversationId = 9;</code>
       * @param value The conversationId to set.
       * @return This builder for chaining.
       */
      public Builder setConversationId(long value) {

        conversationId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * client-server
       * </pre>
       *
       * <code>int64 conversationId = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearConversationId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        conversationId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object conversationName_ = "";
      /**
       * <code>string conversationName = 10;</code>
       * @return The conversationName.
       */
      public java.lang.String getConversationName() {
        java.lang.Object ref = conversationName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          conversationName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string conversationName = 10;</code>
       * @return The bytes for conversationName.
       */
      public com.google.protobuf.ByteString
          getConversationNameBytes() {
        java.lang.Object ref = conversationName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          conversationName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string conversationName = 10;</code>
       * @param value The conversationName to set.
       * @return This builder for chaining.
       */
      public Builder setConversationName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        conversationName_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string conversationName = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearConversationName() {
        conversationName_ = getDefaultInstance().getConversationName();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string conversationName = 10;</code>
       * @param value The bytes for conversationName to set.
       * @return This builder for chaining.
       */
      public Builder setConversationNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        conversationName_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private com.github.im.common.connect.model.proto.Account.AccountInfo fromAccountInfo_;
      private com.google.protobuf.SingleFieldBuilder<
          com.github.im.common.connect.model.proto.Account.AccountInfo, com.github.im.common.connect.model.proto.Account.AccountInfo.Builder, com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder> fromAccountInfoBuilder_;
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo fromAccountInfo = 2;</code>
       * @return Whether the fromAccountInfo field is set.
       */
      public boolean hasFromAccountInfo() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo fromAccountInfo = 2;</code>
       * @return The fromAccountInfo.
       */
      public com.github.im.common.connect.model.proto.Account.AccountInfo getFromAccountInfo() {
        if (fromAccountInfoBuilder_ == null) {
          return fromAccountInfo_ == null ? com.github.im.common.connect.model.proto.Account.AccountInfo.getDefaultInstance() : fromAccountInfo_;
        } else {
          return fromAccountInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo fromAccountInfo = 2;</code>
       */
      public Builder setFromAccountInfo(com.github.im.common.connect.model.proto.Account.AccountInfo value) {
        if (fromAccountInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fromAccountInfo_ = value;
        } else {
          fromAccountInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo fromAccountInfo = 2;</code>
       */
      public Builder setFromAccountInfo(
          com.github.im.common.connect.model.proto.Account.AccountInfo.Builder builderForValue) {
        if (fromAccountInfoBuilder_ == null) {
          fromAccountInfo_ = builderForValue.build();
        } else {
          fromAccountInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo fromAccountInfo = 2;</code>
       */
      public Builder mergeFromAccountInfo(com.github.im.common.connect.model.proto.Account.AccountInfo value) {
        if (fromAccountInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            fromAccountInfo_ != null &&
            fromAccountInfo_ != com.github.im.common.connect.model.proto.Account.AccountInfo.getDefaultInstance()) {
            getFromAccountInfoBuilder().mergeFrom(value);
          } else {
            fromAccountInfo_ = value;
          }
        } else {
          fromAccountInfoBuilder_.mergeFrom(value);
        }
        if (fromAccountInfo_ != null) {
          bitField0_ |= 0x00000010;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo fromAccountInfo = 2;</code>
       */
      public Builder clearFromAccountInfo() {
        bitField0_ = (bitField0_ & ~0x00000010);
        fromAccountInfo_ = null;
        if (fromAccountInfoBuilder_ != null) {
          fromAccountInfoBuilder_.dispose();
          fromAccountInfoBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo fromAccountInfo = 2;</code>
       */
      public com.github.im.common.connect.model.proto.Account.AccountInfo.Builder getFromAccountInfoBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getFromAccountInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo fromAccountInfo = 2;</code>
       */
      public com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder getFromAccountInfoOrBuilder() {
        if (fromAccountInfoBuilder_ != null) {
          return fromAccountInfoBuilder_.getMessageOrBuilder();
        } else {
          return fromAccountInfo_ == null ?
              com.github.im.common.connect.model.proto.Account.AccountInfo.getDefaultInstance() : fromAccountInfo_;
        }
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.AccountInfo fromAccountInfo = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.github.im.common.connect.model.proto.Account.AccountInfo, com.github.im.common.connect.model.proto.Account.AccountInfo.Builder, com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder> 
          getFromAccountInfoFieldBuilder() {
        if (fromAccountInfoBuilder_ == null) {
          fromAccountInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.github.im.common.connect.model.proto.Account.AccountInfo, com.github.im.common.connect.model.proto.Account.AccountInfo.Builder, com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder>(
                  getFromAccountInfo(),
                  getParentForChildren(),
                  isClean());
          fromAccountInfo_ = null;
        }
        return fromAccountInfoBuilder_;
      }

      private com.github.im.common.connect.model.proto.Account.AccountInfo toAccountInfo_;
      private com.google.protobuf.SingleFieldBuilder<
          com.github.im.common.connect.model.proto.Account.AccountInfo, com.github.im.common.connect.model.proto.Account.AccountInfo.Builder, com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder> toAccountInfoBuilder_;
      /**
       * <pre>
       * server-client 需要使用 用于指示推送到的客户端
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.AccountInfo toAccountInfo = 8;</code>
       * @return Whether the toAccountInfo field is set.
       */
      public boolean hasToAccountInfo() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       * server-client 需要使用 用于指示推送到的客户端
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.AccountInfo toAccountInfo = 8;</code>
       * @return The toAccountInfo.
       */
      public com.github.im.common.connect.model.proto.Account.AccountInfo getToAccountInfo() {
        if (toAccountInfoBuilder_ == null) {
          return toAccountInfo_ == null ? com.github.im.common.connect.model.proto.Account.AccountInfo.getDefaultInstance() : toAccountInfo_;
        } else {
          return toAccountInfoBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * server-client 需要使用 用于指示推送到的客户端
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.AccountInfo toAccountInfo = 8;</code>
       */
      public Builder setToAccountInfo(com.github.im.common.connect.model.proto.Account.AccountInfo value) {
        if (toAccountInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          toAccountInfo_ = value;
        } else {
          toAccountInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * server-client 需要使用 用于指示推送到的客户端
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.AccountInfo toAccountInfo = 8;</code>
       */
      public Builder setToAccountInfo(
          com.github.im.common.connect.model.proto.Account.AccountInfo.Builder builderForValue) {
        if (toAccountInfoBuilder_ == null) {
          toAccountInfo_ = builderForValue.build();
        } else {
          toAccountInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * server-client 需要使用 用于指示推送到的客户端
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.AccountInfo toAccountInfo = 8;</code>
       */
      public Builder mergeToAccountInfo(com.github.im.common.connect.model.proto.Account.AccountInfo value) {
        if (toAccountInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000020) != 0) &&
            toAccountInfo_ != null &&
            toAccountInfo_ != com.github.im.common.connect.model.proto.Account.AccountInfo.getDefaultInstance()) {
            getToAccountInfoBuilder().mergeFrom(value);
          } else {
            toAccountInfo_ = value;
          }
        } else {
          toAccountInfoBuilder_.mergeFrom(value);
        }
        if (toAccountInfo_ != null) {
          bitField0_ |= 0x00000020;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * server-client 需要使用 用于指示推送到的客户端
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.AccountInfo toAccountInfo = 8;</code>
       */
      public Builder clearToAccountInfo() {
        bitField0_ = (bitField0_ & ~0x00000020);
        toAccountInfo_ = null;
        if (toAccountInfoBuilder_ != null) {
          toAccountInfoBuilder_.dispose();
          toAccountInfoBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * server-client 需要使用 用于指示推送到的客户端
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.AccountInfo toAccountInfo = 8;</code>
       */
      public com.github.im.common.connect.model.proto.Account.AccountInfo.Builder getToAccountInfoBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getToAccountInfoFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * server-client 需要使用 用于指示推送到的客户端
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.AccountInfo toAccountInfo = 8;</code>
       */
      public com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder getToAccountInfoOrBuilder() {
        if (toAccountInfoBuilder_ != null) {
          return toAccountInfoBuilder_.getMessageOrBuilder();
        } else {
          return toAccountInfo_ == null ?
              com.github.im.common.connect.model.proto.Account.AccountInfo.getDefaultInstance() : toAccountInfo_;
        }
      }
      /**
       * <pre>
       * server-client 需要使用 用于指示推送到的客户端
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.AccountInfo toAccountInfo = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.github.im.common.connect.model.proto.Account.AccountInfo, com.github.im.common.connect.model.proto.Account.AccountInfo.Builder, com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder> 
          getToAccountInfoFieldBuilder() {
        if (toAccountInfoBuilder_ == null) {
          toAccountInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.github.im.common.connect.model.proto.Account.AccountInfo, com.github.im.common.connect.model.proto.Account.AccountInfo.Builder, com.github.im.common.connect.model.proto.Account.AccountInfoOrBuilder>(
                  getToAccountInfo(),
                  getParentForChildren(),
                  isClean());
          toAccountInfo_ = null;
        }
        return toAccountInfoBuilder_;
      }

      private int clientTimeStamp_ ;
      /**
       * <code>sint32 clientTimeStamp = 7;</code>
       * @return The clientTimeStamp.
       */
      @java.lang.Override
      public int getClientTimeStamp() {
        return clientTimeStamp_;
      }
      /**
       * <code>sint32 clientTimeStamp = 7;</code>
       * @param value The clientTimeStamp to set.
       * @return This builder for chaining.
       */
      public Builder setClientTimeStamp(int value) {

        clientTimeStamp_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 clientTimeStamp = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000040);
        clientTimeStamp_ = 0;
        onChanged();
        return this;
      }

      private int serverTimeStamp_ ;
      /**
       * <code>sint32 serverTimeStamp = 12;</code>
       * @return The serverTimeStamp.
       */
      @java.lang.Override
      public int getServerTimeStamp() {
        return serverTimeStamp_;
      }
      /**
       * <code>sint32 serverTimeStamp = 12;</code>
       * @param value The serverTimeStamp to set.
       * @return This builder for chaining.
       */
      public Builder setServerTimeStamp(int value) {

        serverTimeStamp_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 serverTimeStamp = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000080);
        serverTimeStamp_ = 0;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.MessageType type = 6;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.MessageType type = 6;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.MessageType type = 6;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.github.im.common.connect.model.proto.Chat.MessageType getType() {
        com.github.im.common.connect.model.proto.Chat.MessageType result = com.github.im.common.connect.model.proto.Chat.MessageType.forNumber(type_);
        return result == null ? com.github.im.common.connect.model.proto.Chat.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.MessageType type = 6;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.github.im.common.connect.model.proto.Chat.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000100;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.MessageType type = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000100);
        type_ = 0;
        onChanged();
        return this;
      }

      private int messagesStatus_ = 0;
      /**
       * <pre>
       * 消息状态
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.ChatMessage.MessagesStatus messagesStatus = 11;</code>
       * @return The enum numeric value on the wire for messagesStatus.
       */
      @java.lang.Override public int getMessagesStatusValue() {
        return messagesStatus_;
      }
      /**
       * <pre>
       * 消息状态
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.ChatMessage.MessagesStatus messagesStatus = 11;</code>
       * @param value The enum numeric value on the wire for messagesStatus to set.
       * @return This builder for chaining.
       */
      public Builder setMessagesStatusValue(int value) {
        messagesStatus_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息状态
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.ChatMessage.MessagesStatus messagesStatus = 11;</code>
       * @return The messagesStatus.
       */
      @java.lang.Override
      public com.github.im.common.connect.model.proto.Chat.ChatMessage.MessagesStatus getMessagesStatus() {
        com.github.im.common.connect.model.proto.Chat.ChatMessage.MessagesStatus result = com.github.im.common.connect.model.proto.Chat.ChatMessage.MessagesStatus.forNumber(messagesStatus_);
        return result == null ? com.github.im.common.connect.model.proto.Chat.ChatMessage.MessagesStatus.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 消息状态
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.ChatMessage.MessagesStatus messagesStatus = 11;</code>
       * @param value The messagesStatus to set.
       * @return This builder for chaining.
       */
      public Builder setMessagesStatus(com.github.im.common.connect.model.proto.Chat.ChatMessage.MessagesStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000200;
        messagesStatus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息状态
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.ChatMessage.MessagesStatus messagesStatus = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessagesStatus() {
        bitField0_ = (bitField0_ & ~0x00000200);
        messagesStatus_ = 0;
        onChanged();
        return this;
      }

      private long sequenceId_ ;
      /**
       * <pre>
       * generateBy server
       * </pre>
       *
       * <code>int64 sequenceId = 5;</code>
       * @return The sequenceId.
       */
      @java.lang.Override
      public long getSequenceId() {
        return sequenceId_;
      }
      /**
       * <pre>
       * generateBy server
       * </pre>
       *
       * <code>int64 sequenceId = 5;</code>
       * @param value The sequenceId to set.
       * @return This builder for chaining.
       */
      public Builder setSequenceId(long value) {

        sequenceId_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * generateBy server
       * </pre>
       *
       * <code>int64 sequenceId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSequenceId() {
        bitField0_ = (bitField0_ & ~0x00000400);
        sequenceId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.github.im.common.connect.model.proto.ChatMessage)
    }

    // @@protoc_insertion_point(class_scope:com.github.im.common.connect.model.proto.ChatMessage)
    private static final com.github.im.common.connect.model.proto.Chat.ChatMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.im.common.connect.model.proto.Chat.ChatMessage();
    }

    public static com.github.im.common.connect.model.proto.Chat.ChatMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatMessage>
        PARSER = new com.google.protobuf.AbstractParser<ChatMessage>() {
      @java.lang.Override
      public ChatMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ChatMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.im.common.connect.model.proto.Chat.ChatMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_im_common_connect_model_proto_ChatMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_github_im_common_connect_model_proto_ChatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022(com.github.im.common.co" +
      "nnect.model.proto\032\rAccount.proto\"\330\004\n\013Cha" +
      "tMessage\022\r\n\005msgId\030\001 \001(\003\022\017\n\007content\030\003 \001(\t" +
      "\022\026\n\016conversationId\030\t \001(\003\022\030\n\020conversation" +
      "Name\030\n \001(\t\022N\n\017fromAccountInfo\030\002 \001(\01325.co" +
      "m.github.im.common.connect.model.proto.A" +
      "ccountInfo\022L\n\rtoAccountInfo\030\010 \001(\01325.com." +
      "github.im.common.connect.model.proto.Acc" +
      "ountInfo\022\027\n\017clientTimeStamp\030\007 \001(\021\022\027\n\017ser" +
      "verTimeStamp\030\014 \001(\021\022C\n\004type\030\006 \001(\01625.com.g" +
      "ithub.im.common.connect.model.proto.Mess" +
      "ageType\022\\\n\016messagesStatus\030\013 \001(\0162D.com.gi" +
      "thub.im.common.connect.model.proto.ChatM" +
      "essage.MessagesStatus\022\022\n\nsequenceId\030\005 \001(" +
      "\003\"p\n\016MessagesStatus\022\n\n\006REJECT\020\000\022\013\n\007OFFLI" +
      "NE\020\001\022\014\n\010SENTFAIL\020\007\022\013\n\007HISTORY\020\n\022\010\n\004READ\020" +
      "\003\022\n\n\006UNREAD\020\002\022\010\n\004SENT\020\005\022\n\n\006UNSENT\020\013*Q\n\013M" +
      "essageType\022\010\n\004TEXT\020\000\022\014\n\010MARKDOWN\020\005\022\010\n\004FI" +
      "LE\020\001\022\n\n\006STREAM\020\002\022\t\n\005VIDEO\020\003\022\t\n\005IMAGE\020\006B0" +
      "\n(com.github.im.common.connect.model.pro" +
      "toB\004Chatb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.im.common.connect.model.proto.Account.getDescriptor(),
        });
    internal_static_com_github_im_common_connect_model_proto_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_im_common_connect_model_proto_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_github_im_common_connect_model_proto_ChatMessage_descriptor,
        new java.lang.String[] { "MsgId", "Content", "ConversationId", "ConversationName", "FromAccountInfo", "ToAccountInfo", "ClientTimeStamp", "ServerTimeStamp", "Type", "MessagesStatus", "SequenceId", });
    descriptor.resolveAllFeaturesImmutable();
    com.github.im.common.connect.model.proto.Account.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
