// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Notification.proto
// Protobuf Java Version: 4.28.2

package com.github.im.common.connect.model.proto;

public final class Notification {
  private Notification() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      Notification.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NotificationInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.im.common.connect.model.proto.NotificationInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 好友请求申请
     * </pre>
     *
     * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest friendRequest = 1;</code>
     * @return Whether the friendRequest field is set.
     */
    boolean hasFriendRequest();
    /**
     * <pre>
     * 好友请求申请
     * </pre>
     *
     * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest friendRequest = 1;</code>
     * @return The friendRequest.
     */
    com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest getFriendRequest();
    /**
     * <pre>
     * 好友请求申请
     * </pre>
     *
     * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest friendRequest = 1;</code>
     */
    com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequestOrBuilder getFriendRequestOrBuilder();

    com.github.im.common.connect.model.proto.Notification.NotificationInfo.PayloadCase getPayloadCase();
  }
  /**
   * Protobuf type {@code com.github.im.common.connect.model.proto.NotificationInfo}
   */
  public static final class NotificationInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.github.im.common.connect.model.proto.NotificationInfo)
      NotificationInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        NotificationInfo.class.getName());
    }
    // Use NotificationInfo.newBuilder() to construct.
    private NotificationInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private NotificationInfo() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.im.common.connect.model.proto.Notification.internal_static_com_github_im_common_connect_model_proto_NotificationInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.im.common.connect.model.proto.Notification.internal_static_com_github_im_common_connect_model_proto_NotificationInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.im.common.connect.model.proto.Notification.NotificationInfo.class, com.github.im.common.connect.model.proto.Notification.NotificationInfo.Builder.class);
    }

    public interface FriendRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int32 fromUserId = 1;</code>
       * @return The fromUserId.
       */
      int getFromUserId();

      /**
       * <code>int32 toUserId = 2;</code>
       * @return The toUserId.
       */
      int getToUserId();

      /**
       * <code>string fromUserName = 3;</code>
       * @return The fromUserName.
       */
      java.lang.String getFromUserName();
      /**
       * <code>string fromUserName = 3;</code>
       * @return The bytes for fromUserName.
       */
      com.google.protobuf.ByteString
          getFromUserNameBytes();

      /**
       * <code>string toUserName = 4;</code>
       * @return The toUserName.
       */
      java.lang.String getToUserName();
      /**
       * <code>string toUserName = 4;</code>
       * @return The bytes for toUserName.
       */
      com.google.protobuf.ByteString
          getToUserNameBytes();

      /**
       * <code>string remark = 5;</code>
       * @return The remark.
       */
      java.lang.String getRemark();
      /**
       * <code>string remark = 5;</code>
       * @return The bytes for remark.
       */
      com.google.protobuf.ByteString
          getRemarkBytes();

      /**
       * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest type = 6;</code>
       * @return Whether the type field is set.
       */
      boolean hasType();
      /**
       * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest type = 6;</code>
       * @return The type.
       */
      com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest getType();
      /**
       * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest type = 6;</code>
       */
      com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequestOrBuilder getTypeOrBuilder();
    }
    /**
     * Protobuf type {@code com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest}
     */
    public static final class FriendRequest extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest)
        FriendRequestOrBuilder {
    private static final long serialVersionUID = 0L;
      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 28,
          /* patch= */ 2,
          /* suffix= */ "",
          FriendRequest.class.getName());
      }
      // Use FriendRequest.newBuilder() to construct.
      private FriendRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
      }
      private FriendRequest() {
        fromUserName_ = "";
        toUserName_ = "";
        remark_ = "";
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.im.common.connect.model.proto.Notification.internal_static_com_github_im_common_connect_model_proto_NotificationInfo_FriendRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.im.common.connect.model.proto.Notification.internal_static_com_github_im_common_connect_model_proto_NotificationInfo_FriendRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.class, com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.Builder.class);
      }

      /**
       * Protobuf enum {@code com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest.FriendRequestType}
       */
      public enum FriendRequestType
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>ADD = 0;</code>
         */
        ADD(0),
        /**
         * <code>DELETE = 1;</code>
         */
        DELETE(1),
        /**
         * <code>ACCEPT = 2;</code>
         */
        ACCEPT(2),
        /**
         * <code>REJECT = 3;</code>
         */
        REJECT(3),
        UNRECOGNIZED(-1),
        ;

        static {
          com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
            com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
            /* major= */ 4,
            /* minor= */ 28,
            /* patch= */ 2,
            /* suffix= */ "",
            FriendRequestType.class.getName());
        }
        /**
         * <code>ADD = 0;</code>
         */
        public static final int ADD_VALUE = 0;
        /**
         * <code>DELETE = 1;</code>
         */
        public static final int DELETE_VALUE = 1;
        /**
         * <code>ACCEPT = 2;</code>
         */
        public static final int ACCEPT_VALUE = 2;
        /**
         * <code>REJECT = 3;</code>
         */
        public static final int REJECT_VALUE = 3;


        public final int getNumber() {
          if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalArgumentException(
                "Can't get the number of an unknown enum value.");
          }
          return value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static FriendRequestType valueOf(int value) {
          return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static FriendRequestType forNumber(int value) {
          switch (value) {
            case 0: return ADD;
            case 1: return DELETE;
            case 2: return ACCEPT;
            case 3: return REJECT;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<FriendRequestType>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static final com.google.protobuf.Internal.EnumLiteMap<
            FriendRequestType> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<FriendRequestType>() {
                public FriendRequestType findValueByNumber(int number) {
                  return FriendRequestType.forNumber(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalStateException(
                "Can't get the descriptor of an unrecognized enum value.");
          }
          return getDescriptor().getValues().get(ordinal());
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.getDescriptor().getEnumTypes().get(0);
        }

        private static final FriendRequestType[] VALUES = values();

        public static FriendRequestType valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          if (desc.getIndex() == -1) {
            return UNRECOGNIZED;
          }
          return VALUES[desc.getIndex()];
        }

        private final int value;

        private FriendRequestType(int value) {
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest.FriendRequestType)
      }

      private int bitField0_;
      public static final int FROMUSERID_FIELD_NUMBER = 1;
      private int fromUserId_ = 0;
      /**
       * <code>int32 fromUserId = 1;</code>
       * @return The fromUserId.
       */
      @java.lang.Override
      public int getFromUserId() {
        return fromUserId_;
      }

      public static final int TOUSERID_FIELD_NUMBER = 2;
      private int toUserId_ = 0;
      /**
       * <code>int32 toUserId = 2;</code>
       * @return The toUserId.
       */
      @java.lang.Override
      public int getToUserId() {
        return toUserId_;
      }

      public static final int FROMUSERNAME_FIELD_NUMBER = 3;
      @SuppressWarnings("serial")
      private volatile java.lang.Object fromUserName_ = "";
      /**
       * <code>string fromUserName = 3;</code>
       * @return The fromUserName.
       */
      @java.lang.Override
      public java.lang.String getFromUserName() {
        java.lang.Object ref = fromUserName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fromUserName_ = s;
          return s;
        }
      }
      /**
       * <code>string fromUserName = 3;</code>
       * @return The bytes for fromUserName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getFromUserNameBytes() {
        java.lang.Object ref = fromUserName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromUserName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TOUSERNAME_FIELD_NUMBER = 4;
      @SuppressWarnings("serial")
      private volatile java.lang.Object toUserName_ = "";
      /**
       * <code>string toUserName = 4;</code>
       * @return The toUserName.
       */
      @java.lang.Override
      public java.lang.String getToUserName() {
        java.lang.Object ref = toUserName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          toUserName_ = s;
          return s;
        }
      }
      /**
       * <code>string toUserName = 4;</code>
       * @return The bytes for toUserName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getToUserNameBytes() {
        java.lang.Object ref = toUserName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toUserName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int REMARK_FIELD_NUMBER = 5;
      @SuppressWarnings("serial")
      private volatile java.lang.Object remark_ = "";
      /**
       * <code>string remark = 5;</code>
       * @return The remark.
       */
      @java.lang.Override
      public java.lang.String getRemark() {
        java.lang.Object ref = remark_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          remark_ = s;
          return s;
        }
      }
      /**
       * <code>string remark = 5;</code>
       * @return The bytes for remark.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getRemarkBytes() {
        java.lang.Object ref = remark_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          remark_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TYPE_FIELD_NUMBER = 6;
      private com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest type_;
      /**
       * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest type = 6;</code>
       * @return Whether the type field is set.
       */
      @java.lang.Override
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest type = 6;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest getType() {
        return type_ == null ? com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.getDefaultInstance() : type_;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest type = 6;</code>
       */
      @java.lang.Override
      public com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequestOrBuilder getTypeOrBuilder() {
        return type_ == null ? com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.getDefaultInstance() : type_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (fromUserId_ != 0) {
          output.writeInt32(1, fromUserId_);
        }
        if (toUserId_ != 0) {
          output.writeInt32(2, toUserId_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(fromUserName_)) {
          com.google.protobuf.GeneratedMessage.writeString(output, 3, fromUserName_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(toUserName_)) {
          com.google.protobuf.GeneratedMessage.writeString(output, 4, toUserName_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(remark_)) {
          com.google.protobuf.GeneratedMessage.writeString(output, 5, remark_);
        }
        if (((bitField0_ & 0x00000001) != 0)) {
          output.writeMessage(6, getType());
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (fromUserId_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, fromUserId_);
        }
        if (toUserId_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, toUserId_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(fromUserName_)) {
          size += com.google.protobuf.GeneratedMessage.computeStringSize(3, fromUserName_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(toUserName_)) {
          size += com.google.protobuf.GeneratedMessage.computeStringSize(4, toUserName_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(remark_)) {
          size += com.google.protobuf.GeneratedMessage.computeStringSize(5, remark_);
        }
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, getType());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest)) {
          return super.equals(obj);
        }
        com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest other = (com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest) obj;

        if (getFromUserId()
            != other.getFromUserId()) return false;
        if (getToUserId()
            != other.getToUserId()) return false;
        if (!getFromUserName()
            .equals(other.getFromUserName())) return false;
        if (!getToUserName()
            .equals(other.getToUserName())) return false;
        if (!getRemark()
            .equals(other.getRemark())) return false;
        if (hasType() != other.hasType()) return false;
        if (hasType()) {
          if (!getType()
              .equals(other.getType())) return false;
        }
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + FROMUSERID_FIELD_NUMBER;
        hash = (53 * hash) + getFromUserId();
        hash = (37 * hash) + TOUSERID_FIELD_NUMBER;
        hash = (53 * hash) + getToUserId();
        hash = (37 * hash) + FROMUSERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getFromUserName().hashCode();
        hash = (37 * hash) + TOUSERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getToUserName().hashCode();
        hash = (37 * hash) + REMARK_FIELD_NUMBER;
        hash = (53 * hash) + getRemark().hashCode();
        if (hasType()) {
          hash = (37 * hash) + TYPE_FIELD_NUMBER;
          hash = (53 * hash) + getType().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input);
      }

      public static com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest)
          com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.github.im.common.connect.model.proto.Notification.internal_static_com_github_im_common_connect_model_proto_NotificationInfo_FriendRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.github.im.common.connect.model.proto.Notification.internal_static_com_github_im_common_connect_model_proto_NotificationInfo_FriendRequest_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.class, com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.Builder.class);
        }

        // Construct using com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage
                  .alwaysUseFieldBuilders) {
            getTypeFieldBuilder();
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          fromUserId_ = 0;
          toUserId_ = 0;
          fromUserName_ = "";
          toUserName_ = "";
          remark_ = "";
          type_ = null;
          if (typeBuilder_ != null) {
            typeBuilder_.dispose();
            typeBuilder_ = null;
          }
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.github.im.common.connect.model.proto.Notification.internal_static_com_github_im_common_connect_model_proto_NotificationInfo_FriendRequest_descriptor;
        }

        @java.lang.Override
        public com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest getDefaultInstanceForType() {
          return com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.getDefaultInstance();
        }

        @java.lang.Override
        public com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest build() {
          com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest buildPartial() {
          com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest result = new com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.fromUserId_ = fromUserId_;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.toUserId_ = toUserId_;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            result.fromUserName_ = fromUserName_;
          }
          if (((from_bitField0_ & 0x00000008) != 0)) {
            result.toUserName_ = toUserName_;
          }
          if (((from_bitField0_ & 0x00000010) != 0)) {
            result.remark_ = remark_;
          }
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000020) != 0)) {
            result.type_ = typeBuilder_ == null
                ? type_
                : typeBuilder_.build();
            to_bitField0_ |= 0x00000001;
          }
          result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest) {
            return mergeFrom((com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest other) {
          if (other == com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.getDefaultInstance()) return this;
          if (other.getFromUserId() != 0) {
            setFromUserId(other.getFromUserId());
          }
          if (other.getToUserId() != 0) {
            setToUserId(other.getToUserId());
          }
          if (!other.getFromUserName().isEmpty()) {
            fromUserName_ = other.fromUserName_;
            bitField0_ |= 0x00000004;
            onChanged();
          }
          if (!other.getToUserName().isEmpty()) {
            toUserName_ = other.toUserName_;
            bitField0_ |= 0x00000008;
            onChanged();
          }
          if (!other.getRemark().isEmpty()) {
            remark_ = other.remark_;
            bitField0_ |= 0x00000010;
            onChanged();
          }
          if (other.hasType()) {
            mergeType(other.getType());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 8: {
                  fromUserId_ = input.readInt32();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 8
                case 16: {
                  toUserId_ = input.readInt32();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 16
                case 26: {
                  fromUserName_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000004;
                  break;
                } // case 26
                case 34: {
                  toUserName_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000008;
                  break;
                } // case 34
                case 42: {
                  remark_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000010;
                  break;
                } // case 42
                case 50: {
                  input.readMessage(
                      getTypeFieldBuilder().getBuilder(),
                      extensionRegistry);
                  bitField0_ |= 0x00000020;
                  break;
                } // case 50
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private int fromUserId_ ;
        /**
         * <code>int32 fromUserId = 1;</code>
         * @return The fromUserId.
         */
        @java.lang.Override
        public int getFromUserId() {
          return fromUserId_;
        }
        /**
         * <code>int32 fromUserId = 1;</code>
         * @param value The fromUserId to set.
         * @return This builder for chaining.
         */
        public Builder setFromUserId(int value) {

          fromUserId_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>int32 fromUserId = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearFromUserId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          fromUserId_ = 0;
          onChanged();
          return this;
        }

        private int toUserId_ ;
        /**
         * <code>int32 toUserId = 2;</code>
         * @return The toUserId.
         */
        @java.lang.Override
        public int getToUserId() {
          return toUserId_;
        }
        /**
         * <code>int32 toUserId = 2;</code>
         * @param value The toUserId to set.
         * @return This builder for chaining.
         */
        public Builder setToUserId(int value) {

          toUserId_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>int32 toUserId = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearToUserId() {
          bitField0_ = (bitField0_ & ~0x00000002);
          toUserId_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object fromUserName_ = "";
        /**
         * <code>string fromUserName = 3;</code>
         * @return The fromUserName.
         */
        public java.lang.String getFromUserName() {
          java.lang.Object ref = fromUserName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            fromUserName_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string fromUserName = 3;</code>
         * @return The bytes for fromUserName.
         */
        public com.google.protobuf.ByteString
            getFromUserNameBytes() {
          java.lang.Object ref = fromUserName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            fromUserName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string fromUserName = 3;</code>
         * @param value The fromUserName to set.
         * @return This builder for chaining.
         */
        public Builder setFromUserName(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          fromUserName_ = value;
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }
        /**
         * <code>string fromUserName = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearFromUserName() {
          fromUserName_ = getDefaultInstance().getFromUserName();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
          return this;
        }
        /**
         * <code>string fromUserName = 3;</code>
         * @param value The bytes for fromUserName to set.
         * @return This builder for chaining.
         */
        public Builder setFromUserNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          fromUserName_ = value;
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }

        private java.lang.Object toUserName_ = "";
        /**
         * <code>string toUserName = 4;</code>
         * @return The toUserName.
         */
        public java.lang.String getToUserName() {
          java.lang.Object ref = toUserName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            toUserName_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string toUserName = 4;</code>
         * @return The bytes for toUserName.
         */
        public com.google.protobuf.ByteString
            getToUserNameBytes() {
          java.lang.Object ref = toUserName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            toUserName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string toUserName = 4;</code>
         * @param value The toUserName to set.
         * @return This builder for chaining.
         */
        public Builder setToUserName(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          toUserName_ = value;
          bitField0_ |= 0x00000008;
          onChanged();
          return this;
        }
        /**
         * <code>string toUserName = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearToUserName() {
          toUserName_ = getDefaultInstance().getToUserName();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
          return this;
        }
        /**
         * <code>string toUserName = 4;</code>
         * @param value The bytes for toUserName to set.
         * @return This builder for chaining.
         */
        public Builder setToUserNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          toUserName_ = value;
          bitField0_ |= 0x00000008;
          onChanged();
          return this;
        }

        private java.lang.Object remark_ = "";
        /**
         * <code>string remark = 5;</code>
         * @return The remark.
         */
        public java.lang.String getRemark() {
          java.lang.Object ref = remark_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            remark_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string remark = 5;</code>
         * @return The bytes for remark.
         */
        public com.google.protobuf.ByteString
            getRemarkBytes() {
          java.lang.Object ref = remark_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            remark_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string remark = 5;</code>
         * @param value The remark to set.
         * @return This builder for chaining.
         */
        public Builder setRemark(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          remark_ = value;
          bitField0_ |= 0x00000010;
          onChanged();
          return this;
        }
        /**
         * <code>string remark = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearRemark() {
          remark_ = getDefaultInstance().getRemark();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
          return this;
        }
        /**
         * <code>string remark = 5;</code>
         * @param value The bytes for remark to set.
         * @return This builder for chaining.
         */
        public Builder setRemarkBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          remark_ = value;
          bitField0_ |= 0x00000010;
          onChanged();
          return this;
        }

        private com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest type_;
        private com.google.protobuf.SingleFieldBuilder<
            com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest, com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.Builder, com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequestOrBuilder> typeBuilder_;
        /**
         * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest type = 6;</code>
         * @return Whether the type field is set.
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000020) != 0);
        }
        /**
         * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest type = 6;</code>
         * @return The type.
         */
        public com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest getType() {
          if (typeBuilder_ == null) {
            return type_ == null ? com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.getDefaultInstance() : type_;
          } else {
            return typeBuilder_.getMessage();
          }
        }
        /**
         * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest type = 6;</code>
         */
        public Builder setType(com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest value) {
          if (typeBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            type_ = value;
          } else {
            typeBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000020;
          onChanged();
          return this;
        }
        /**
         * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest type = 6;</code>
         */
        public Builder setType(
            com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.Builder builderForValue) {
          if (typeBuilder_ == null) {
            type_ = builderForValue.build();
          } else {
            typeBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000020;
          onChanged();
          return this;
        }
        /**
         * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest type = 6;</code>
         */
        public Builder mergeType(com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest value) {
          if (typeBuilder_ == null) {
            if (((bitField0_ & 0x00000020) != 0) &&
              type_ != null &&
              type_ != com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.getDefaultInstance()) {
              getTypeBuilder().mergeFrom(value);
            } else {
              type_ = value;
            }
          } else {
            typeBuilder_.mergeFrom(value);
          }
          if (type_ != null) {
            bitField0_ |= 0x00000020;
            onChanged();
          }
          return this;
        }
        /**
         * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest type = 6;</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000020);
          type_ = null;
          if (typeBuilder_ != null) {
            typeBuilder_.dispose();
            typeBuilder_ = null;
          }
          onChanged();
          return this;
        }
        /**
         * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest type = 6;</code>
         */
        public com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.Builder getTypeBuilder() {
          bitField0_ |= 0x00000020;
          onChanged();
          return getTypeFieldBuilder().getBuilder();
        }
        /**
         * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest type = 6;</code>
         */
        public com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequestOrBuilder getTypeOrBuilder() {
          if (typeBuilder_ != null) {
            return typeBuilder_.getMessageOrBuilder();
          } else {
            return type_ == null ?
                com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.getDefaultInstance() : type_;
          }
        }
        /**
         * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest type = 6;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<
            com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest, com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.Builder, com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequestOrBuilder> 
            getTypeFieldBuilder() {
          if (typeBuilder_ == null) {
            typeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest, com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.Builder, com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequestOrBuilder>(
                    getType(),
                    getParentForChildren(),
                    isClean());
            type_ = null;
          }
          return typeBuilder_;
        }

        // @@protoc_insertion_point(builder_scope:com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest)
      }

      // @@protoc_insertion_point(class_scope:com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest)
      private static final com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest();
      }

      public static com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<FriendRequest>
          PARSER = new com.google.protobuf.AbstractParser<FriendRequest>() {
        @java.lang.Override
        public FriendRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<FriendRequest> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<FriendRequest> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int payloadCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object payload_;
    public enum PayloadCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      FRIENDREQUEST(1),
      PAYLOAD_NOT_SET(0);
      private final int value;
      private PayloadCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PayloadCase valueOf(int value) {
        return forNumber(value);
      }

      public static PayloadCase forNumber(int value) {
        switch (value) {
          case 1: return FRIENDREQUEST;
          case 0: return PAYLOAD_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PayloadCase
    getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public static final int FRIENDREQUEST_FIELD_NUMBER = 1;
    /**
     * <pre>
     * 好友请求申请
     * </pre>
     *
     * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest friendRequest = 1;</code>
     * @return Whether the friendRequest field is set.
     */
    @java.lang.Override
    public boolean hasFriendRequest() {
      return payloadCase_ == 1;
    }
    /**
     * <pre>
     * 好友请求申请
     * </pre>
     *
     * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest friendRequest = 1;</code>
     * @return The friendRequest.
     */
    @java.lang.Override
    public com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest getFriendRequest() {
      if (payloadCase_ == 1) {
         return (com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest) payload_;
      }
      return com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.getDefaultInstance();
    }
    /**
     * <pre>
     * 好友请求申请
     * </pre>
     *
     * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest friendRequest = 1;</code>
     */
    @java.lang.Override
    public com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequestOrBuilder getFriendRequestOrBuilder() {
      if (payloadCase_ == 1) {
         return (com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest) payload_;
      }
      return com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (payloadCase_ == 1) {
        output.writeMessage(1, (com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest) payload_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (payloadCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest) payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.im.common.connect.model.proto.Notification.NotificationInfo)) {
        return super.equals(obj);
      }
      com.github.im.common.connect.model.proto.Notification.NotificationInfo other = (com.github.im.common.connect.model.proto.Notification.NotificationInfo) obj;

      if (!getPayloadCase().equals(other.getPayloadCase())) return false;
      switch (payloadCase_) {
        case 1:
          if (!getFriendRequest()
              .equals(other.getFriendRequest())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (payloadCase_) {
        case 1:
          hash = (37 * hash) + FRIENDREQUEST_FIELD_NUMBER;
          hash = (53 * hash) + getFriendRequest().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.im.common.connect.model.proto.Notification.NotificationInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.im.common.connect.model.proto.Notification.NotificationInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.Notification.NotificationInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.im.common.connect.model.proto.Notification.NotificationInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.Notification.NotificationInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.im.common.connect.model.proto.Notification.NotificationInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.Notification.NotificationInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.im.common.connect.model.proto.Notification.NotificationInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.im.common.connect.model.proto.Notification.NotificationInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.im.common.connect.model.proto.Notification.NotificationInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.Notification.NotificationInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.im.common.connect.model.proto.Notification.NotificationInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.im.common.connect.model.proto.Notification.NotificationInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.im.common.connect.model.proto.NotificationInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.im.common.connect.model.proto.NotificationInfo)
        com.github.im.common.connect.model.proto.Notification.NotificationInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.im.common.connect.model.proto.Notification.internal_static_com_github_im_common_connect_model_proto_NotificationInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.im.common.connect.model.proto.Notification.internal_static_com_github_im_common_connect_model_proto_NotificationInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.im.common.connect.model.proto.Notification.NotificationInfo.class, com.github.im.common.connect.model.proto.Notification.NotificationInfo.Builder.class);
      }

      // Construct using com.github.im.common.connect.model.proto.Notification.NotificationInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (friendRequestBuilder_ != null) {
          friendRequestBuilder_.clear();
        }
        payloadCase_ = 0;
        payload_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.im.common.connect.model.proto.Notification.internal_static_com_github_im_common_connect_model_proto_NotificationInfo_descriptor;
      }

      @java.lang.Override
      public com.github.im.common.connect.model.proto.Notification.NotificationInfo getDefaultInstanceForType() {
        return com.github.im.common.connect.model.proto.Notification.NotificationInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.im.common.connect.model.proto.Notification.NotificationInfo build() {
        com.github.im.common.connect.model.proto.Notification.NotificationInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.im.common.connect.model.proto.Notification.NotificationInfo buildPartial() {
        com.github.im.common.connect.model.proto.Notification.NotificationInfo result = new com.github.im.common.connect.model.proto.Notification.NotificationInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.im.common.connect.model.proto.Notification.NotificationInfo result) {
        int from_bitField0_ = bitField0_;
      }

      private void buildPartialOneofs(com.github.im.common.connect.model.proto.Notification.NotificationInfo result) {
        result.payloadCase_ = payloadCase_;
        result.payload_ = this.payload_;
        if (payloadCase_ == 1 &&
            friendRequestBuilder_ != null) {
          result.payload_ = friendRequestBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.im.common.connect.model.proto.Notification.NotificationInfo) {
          return mergeFrom((com.github.im.common.connect.model.proto.Notification.NotificationInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.im.common.connect.model.proto.Notification.NotificationInfo other) {
        if (other == com.github.im.common.connect.model.proto.Notification.NotificationInfo.getDefaultInstance()) return this;
        switch (other.getPayloadCase()) {
          case FRIENDREQUEST: {
            mergeFriendRequest(other.getFriendRequest());
            break;
          }
          case PAYLOAD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getFriendRequestFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 1;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int payloadCase_ = 0;
      private java.lang.Object payload_;
      public PayloadCase
          getPayloadCase() {
        return PayloadCase.forNumber(
            payloadCase_);
      }

      public Builder clearPayload() {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilder<
          com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest, com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.Builder, com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequestOrBuilder> friendRequestBuilder_;
      /**
       * <pre>
       * 好友请求申请
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest friendRequest = 1;</code>
       * @return Whether the friendRequest field is set.
       */
      @java.lang.Override
      public boolean hasFriendRequest() {
        return payloadCase_ == 1;
      }
      /**
       * <pre>
       * 好友请求申请
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest friendRequest = 1;</code>
       * @return The friendRequest.
       */
      @java.lang.Override
      public com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest getFriendRequest() {
        if (friendRequestBuilder_ == null) {
          if (payloadCase_ == 1) {
            return (com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest) payload_;
          }
          return com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.getDefaultInstance();
        } else {
          if (payloadCase_ == 1) {
            return friendRequestBuilder_.getMessage();
          }
          return com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * 好友请求申请
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest friendRequest = 1;</code>
       */
      public Builder setFriendRequest(com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest value) {
        if (friendRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          friendRequestBuilder_.setMessage(value);
        }
        payloadCase_ = 1;
        return this;
      }
      /**
       * <pre>
       * 好友请求申请
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest friendRequest = 1;</code>
       */
      public Builder setFriendRequest(
          com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.Builder builderForValue) {
        if (friendRequestBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          friendRequestBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 1;
        return this;
      }
      /**
       * <pre>
       * 好友请求申请
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest friendRequest = 1;</code>
       */
      public Builder mergeFriendRequest(com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest value) {
        if (friendRequestBuilder_ == null) {
          if (payloadCase_ == 1 &&
              payload_ != com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.getDefaultInstance()) {
            payload_ = com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.newBuilder((com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 1) {
            friendRequestBuilder_.mergeFrom(value);
          } else {
            friendRequestBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 1;
        return this;
      }
      /**
       * <pre>
       * 好友请求申请
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest friendRequest = 1;</code>
       */
      public Builder clearFriendRequest() {
        if (friendRequestBuilder_ == null) {
          if (payloadCase_ == 1) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 1) {
            payloadCase_ = 0;
            payload_ = null;
          }
          friendRequestBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 好友请求申请
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest friendRequest = 1;</code>
       */
      public com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.Builder getFriendRequestBuilder() {
        return getFriendRequestFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 好友请求申请
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest friendRequest = 1;</code>
       */
      @java.lang.Override
      public com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequestOrBuilder getFriendRequestOrBuilder() {
        if ((payloadCase_ == 1) && (friendRequestBuilder_ != null)) {
          return friendRequestBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 1) {
            return (com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest) payload_;
          }
          return com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * 好友请求申请
       * </pre>
       *
       * <code>.com.github.im.common.connect.model.proto.NotificationInfo.FriendRequest friendRequest = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest, com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.Builder, com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequestOrBuilder> 
          getFriendRequestFieldBuilder() {
        if (friendRequestBuilder_ == null) {
          if (!(payloadCase_ == 1)) {
            payload_ = com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.getDefaultInstance();
          }
          friendRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest, com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest.Builder, com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequestOrBuilder>(
                  (com.github.im.common.connect.model.proto.Notification.NotificationInfo.FriendRequest) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 1;
        onChanged();
        return friendRequestBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.github.im.common.connect.model.proto.NotificationInfo)
    }

    // @@protoc_insertion_point(class_scope:com.github.im.common.connect.model.proto.NotificationInfo)
    private static final com.github.im.common.connect.model.proto.Notification.NotificationInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.im.common.connect.model.proto.Notification.NotificationInfo();
    }

    public static com.github.im.common.connect.model.proto.Notification.NotificationInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NotificationInfo>
        PARSER = new com.google.protobuf.AbstractParser<NotificationInfo>() {
      @java.lang.Override
      public NotificationInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NotificationInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NotificationInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.im.common.connect.model.proto.Notification.NotificationInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_im_common_connect_model_proto_NotificationInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_github_im_common_connect_model_proto_NotificationInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_im_common_connect_model_proto_NotificationInfo_FriendRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_github_im_common_connect_model_proto_NotificationInfo_FriendRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022Notification.proto\022(com.github.im.comm" +
      "on.connect.model.proto\"\214\003\n\020NotificationI" +
      "nfo\022a\n\rfriendRequest\030\001 \001(\0132H.com.github." +
      "im.common.connect.model.proto.Notificati" +
      "onInfo.FriendRequestH\000\032\211\002\n\rFriendRequest" +
      "\022\022\n\nfromUserId\030\001 \001(\005\022\020\n\010toUserId\030\002 \001(\005\022\024" +
      "\n\014fromUserName\030\003 \001(\t\022\022\n\ntoUserName\030\004 \001(\t" +
      "\022\016\n\006remark\030\005 \001(\t\022V\n\004type\030\006 \001(\0132H.com.git" +
      "hub.im.common.connect.model.proto.Notifi" +
      "cationInfo.FriendRequest\"@\n\021FriendReques" +
      "tType\022\007\n\003ADD\020\000\022\n\n\006DELETE\020\001\022\n\n\006ACCEPT\020\002\022\n" +
      "\n\006REJECT\020\003B\t\n\007payloadB8\n(com.github.im.c" +
      "ommon.connect.model.protoB\014Notificationb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_github_im_common_connect_model_proto_NotificationInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_im_common_connect_model_proto_NotificationInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_github_im_common_connect_model_proto_NotificationInfo_descriptor,
        new java.lang.String[] { "FriendRequest", "Payload", });
    internal_static_com_github_im_common_connect_model_proto_NotificationInfo_FriendRequest_descriptor =
      internal_static_com_github_im_common_connect_model_proto_NotificationInfo_descriptor.getNestedTypes().get(0);
    internal_static_com_github_im_common_connect_model_proto_NotificationInfo_FriendRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_github_im_common_connect_model_proto_NotificationInfo_FriendRequest_descriptor,
        new java.lang.String[] { "FromUserId", "ToUserId", "FromUserName", "ToUserName", "Remark", "Type", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
