// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: UserInfoProto.proto
// Protobuf Java Version: 4.28.2

package com.github.im.common.connect.model.proto;

public final class User {
  private User() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      User.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.github.im.common.connect.model.proto.PlatformType}
   */
  public enum PlatformType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>WEB = 0;</code>
     */
    WEB(0),
    /**
     * <code>ANDROID = 1;</code>
     */
    ANDROID(1),
    /**
     * <code>IOS = 2;</code>
     */
    IOS(2),
    /**
     * <code>WINDOWS = 3;</code>
     */
    WINDOWS(3),
    /**
     * <code>MAC = 4;</code>
     */
    MAC(4),
    /**
     * <code>LINUX = 5;</code>
     */
    LINUX(5),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        PlatformType.class.getName());
    }
    /**
     * <code>WEB = 0;</code>
     */
    public static final int WEB_VALUE = 0;
    /**
     * <code>ANDROID = 1;</code>
     */
    public static final int ANDROID_VALUE = 1;
    /**
     * <code>IOS = 2;</code>
     */
    public static final int IOS_VALUE = 2;
    /**
     * <code>WINDOWS = 3;</code>
     */
    public static final int WINDOWS_VALUE = 3;
    /**
     * <code>MAC = 4;</code>
     */
    public static final int MAC_VALUE = 4;
    /**
     * <code>LINUX = 5;</code>
     */
    public static final int LINUX_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PlatformType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static PlatformType forNumber(int value) {
      switch (value) {
        case 0: return WEB;
        case 1: return ANDROID;
        case 2: return IOS;
        case 3: return WINDOWS;
        case 4: return MAC;
        case 5: return LINUX;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PlatformType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PlatformType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PlatformType>() {
            public PlatformType findValueByNumber(int number) {
              return PlatformType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.im.common.connect.model.proto.User.getDescriptor().getEnumTypes().get(0);
    }

    private static final PlatformType[] VALUES = values();

    public static PlatformType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PlatformType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.github.im.common.connect.model.proto.PlatformType)
  }

  public interface UserInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.im.common.connect.model.proto.UserInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * *
     * {&#64;link UserInfo#getUsername}
     * </pre>
     *
     * <code>string username = 1;</code>
     * @return The username.
     */
    java.lang.String getUsername();
    /**
     * <pre>
     * *
     * {&#64;link UserInfo#getUsername}
     * </pre>
     *
     * <code>string username = 1;</code>
     * @return The bytes for username.
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>int64 userId = 2;</code>
     * @return The userId.
     */
    long getUserId();

    /**
     * <code>string eMail = 3;</code>
     * @return The eMail.
     */
    java.lang.String getEMail();
    /**
     * <code>string eMail = 3;</code>
     * @return The bytes for eMail.
     */
    com.google.protobuf.ByteString
        getEMailBytes();

    /**
     * <code>string accessToken = 4;</code>
     * @return The accessToken.
     */
    java.lang.String getAccessToken();
    /**
     * <code>string accessToken = 4;</code>
     * @return The bytes for accessToken.
     */
    com.google.protobuf.ByteString
        getAccessTokenBytes();

    /**
     * <code>.com.github.im.common.connect.model.proto.PlatformType platformType = 5;</code>
     * @return The enum numeric value on the wire for platformType.
     */
    int getPlatformTypeValue();
    /**
     * <code>.com.github.im.common.connect.model.proto.PlatformType platformType = 5;</code>
     * @return The platformType.
     */
    com.github.im.common.connect.model.proto.User.PlatformType getPlatformType();
  }
  /**
   * Protobuf type {@code com.github.im.common.connect.model.proto.UserInfo}
   */
  public static final class UserInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.github.im.common.connect.model.proto.UserInfo)
      UserInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        UserInfo.class.getName());
    }
    // Use UserInfo.newBuilder() to construct.
    private UserInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private UserInfo() {
      username_ = "";
      eMail_ = "";
      accessToken_ = "";
      platformType_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.im.common.connect.model.proto.User.internal_static_com_github_im_common_connect_model_proto_UserInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.im.common.connect.model.proto.User.internal_static_com_github_im_common_connect_model_proto_UserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.im.common.connect.model.proto.User.UserInfo.class, com.github.im.common.connect.model.proto.User.UserInfo.Builder.class);
    }

    public static final int USERNAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object username_ = "";
    /**
     * <pre>
     * *
     * {&#64;link UserInfo#getUsername}
     * </pre>
     *
     * <code>string username = 1;</code>
     * @return The username.
     */
    @java.lang.Override
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * *
     * {&#64;link UserInfo#getUsername}
     * </pre>
     *
     * <code>string username = 1;</code>
     * @return The bytes for username.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private long userId_ = 0L;
    /**
     * <code>int64 userId = 2;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object eMail_ = "";
    /**
     * <code>string eMail = 3;</code>
     * @return The eMail.
     */
    @java.lang.Override
    public java.lang.String getEMail() {
      java.lang.Object ref = eMail_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eMail_ = s;
        return s;
      }
    }
    /**
     * <code>string eMail = 3;</code>
     * @return The bytes for eMail.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEMailBytes() {
      java.lang.Object ref = eMail_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eMail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCESSTOKEN_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object accessToken_ = "";
    /**
     * <code>string accessToken = 4;</code>
     * @return The accessToken.
     */
    @java.lang.Override
    public java.lang.String getAccessToken() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accessToken_ = s;
        return s;
      }
    }
    /**
     * <code>string accessToken = 4;</code>
     * @return The bytes for accessToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccessTokenBytes() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accessToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLATFORMTYPE_FIELD_NUMBER = 5;
    private int platformType_ = 0;
    /**
     * <code>.com.github.im.common.connect.model.proto.PlatformType platformType = 5;</code>
     * @return The enum numeric value on the wire for platformType.
     */
    @java.lang.Override public int getPlatformTypeValue() {
      return platformType_;
    }
    /**
     * <code>.com.github.im.common.connect.model.proto.PlatformType platformType = 5;</code>
     * @return The platformType.
     */
    @java.lang.Override public com.github.im.common.connect.model.proto.User.PlatformType getPlatformType() {
      com.github.im.common.connect.model.proto.User.PlatformType result = com.github.im.common.connect.model.proto.User.PlatformType.forNumber(platformType_);
      return result == null ? com.github.im.common.connect.model.proto.User.PlatformType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(username_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, username_);
      }
      if (userId_ != 0L) {
        output.writeInt64(2, userId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eMail_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, eMail_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(accessToken_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, accessToken_);
      }
      if (platformType_ != com.github.im.common.connect.model.proto.User.PlatformType.WEB.getNumber()) {
        output.writeEnum(5, platformType_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(username_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, username_);
      }
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, userId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eMail_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, eMail_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(accessToken_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, accessToken_);
      }
      if (platformType_ != com.github.im.common.connect.model.proto.User.PlatformType.WEB.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, platformType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.im.common.connect.model.proto.User.UserInfo)) {
        return super.equals(obj);
      }
      com.github.im.common.connect.model.proto.User.UserInfo other = (com.github.im.common.connect.model.proto.User.UserInfo) obj;

      if (!getUsername()
          .equals(other.getUsername())) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (!getEMail()
          .equals(other.getEMail())) return false;
      if (!getAccessToken()
          .equals(other.getAccessToken())) return false;
      if (platformType_ != other.platformType_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEMail().hashCode();
      hash = (37 * hash) + ACCESSTOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getAccessToken().hashCode();
      hash = (37 * hash) + PLATFORMTYPE_FIELD_NUMBER;
      hash = (53 * hash) + platformType_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.im.common.connect.model.proto.User.UserInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.im.common.connect.model.proto.User.UserInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.User.UserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.im.common.connect.model.proto.User.UserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.User.UserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.im.common.connect.model.proto.User.UserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.User.UserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.im.common.connect.model.proto.User.UserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.im.common.connect.model.proto.User.UserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.im.common.connect.model.proto.User.UserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.im.common.connect.model.proto.User.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.im.common.connect.model.proto.User.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.im.common.connect.model.proto.User.UserInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.im.common.connect.model.proto.UserInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.im.common.connect.model.proto.UserInfo)
        com.github.im.common.connect.model.proto.User.UserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.im.common.connect.model.proto.User.internal_static_com_github_im_common_connect_model_proto_UserInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.im.common.connect.model.proto.User.internal_static_com_github_im_common_connect_model_proto_UserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.im.common.connect.model.proto.User.UserInfo.class, com.github.im.common.connect.model.proto.User.UserInfo.Builder.class);
      }

      // Construct using com.github.im.common.connect.model.proto.User.UserInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        username_ = "";
        userId_ = 0L;
        eMail_ = "";
        accessToken_ = "";
        platformType_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.im.common.connect.model.proto.User.internal_static_com_github_im_common_connect_model_proto_UserInfo_descriptor;
      }

      @java.lang.Override
      public com.github.im.common.connect.model.proto.User.UserInfo getDefaultInstanceForType() {
        return com.github.im.common.connect.model.proto.User.UserInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.im.common.connect.model.proto.User.UserInfo build() {
        com.github.im.common.connect.model.proto.User.UserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.im.common.connect.model.proto.User.UserInfo buildPartial() {
        com.github.im.common.connect.model.proto.User.UserInfo result = new com.github.im.common.connect.model.proto.User.UserInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.im.common.connect.model.proto.User.UserInfo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.username_ = username_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.eMail_ = eMail_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.accessToken_ = accessToken_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.platformType_ = platformType_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.im.common.connect.model.proto.User.UserInfo) {
          return mergeFrom((com.github.im.common.connect.model.proto.User.UserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.im.common.connect.model.proto.User.UserInfo other) {
        if (other == com.github.im.common.connect.model.proto.User.UserInfo.getDefaultInstance()) return this;
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (!other.getEMail().isEmpty()) {
          eMail_ = other.eMail_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getAccessToken().isEmpty()) {
          accessToken_ = other.accessToken_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.platformType_ != 0) {
          setPlatformTypeValue(other.getPlatformTypeValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                username_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                userId_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                eMail_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                accessToken_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                platformType_ = input.readEnum();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object username_ = "";
      /**
       * <pre>
       * *
       * {&#64;link UserInfo#getUsername}
       * </pre>
       *
       * <code>string username = 1;</code>
       * @return The username.
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * *
       * {&#64;link UserInfo#getUsername}
       * </pre>
       *
       * <code>string username = 1;</code>
       * @return The bytes for username.
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * *
       * {&#64;link UserInfo#getUsername}
       * </pre>
       *
       * <code>string username = 1;</code>
       * @param value The username to set.
       * @return This builder for chaining.
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        username_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * *
       * {&#64;link UserInfo#getUsername}
       * </pre>
       *
       * <code>string username = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsername() {
        username_ = getDefaultInstance().getUsername();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * *
       * {&#64;link UserInfo#getUsername}
       * </pre>
       *
       * <code>string username = 1;</code>
       * @param value The bytes for username to set.
       * @return This builder for chaining.
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        username_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 userId = 2;</code>
       * @return The userId.
       */
      @java.lang.Override
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 2;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {

        userId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object eMail_ = "";
      /**
       * <code>string eMail = 3;</code>
       * @return The eMail.
       */
      public java.lang.String getEMail() {
        java.lang.Object ref = eMail_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          eMail_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string eMail = 3;</code>
       * @return The bytes for eMail.
       */
      public com.google.protobuf.ByteString
          getEMailBytes() {
        java.lang.Object ref = eMail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eMail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string eMail = 3;</code>
       * @param value The eMail to set.
       * @return This builder for chaining.
       */
      public Builder setEMail(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        eMail_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string eMail = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEMail() {
        eMail_ = getDefaultInstance().getEMail();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string eMail = 3;</code>
       * @param value The bytes for eMail to set.
       * @return This builder for chaining.
       */
      public Builder setEMailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        eMail_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object accessToken_ = "";
      /**
       * <code>string accessToken = 4;</code>
       * @return The accessToken.
       */
      public java.lang.String getAccessToken() {
        java.lang.Object ref = accessToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accessToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string accessToken = 4;</code>
       * @return The bytes for accessToken.
       */
      public com.google.protobuf.ByteString
          getAccessTokenBytes() {
        java.lang.Object ref = accessToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accessToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string accessToken = 4;</code>
       * @param value The accessToken to set.
       * @return This builder for chaining.
       */
      public Builder setAccessToken(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        accessToken_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string accessToken = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccessToken() {
        accessToken_ = getDefaultInstance().getAccessToken();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string accessToken = 4;</code>
       * @param value The bytes for accessToken to set.
       * @return This builder for chaining.
       */
      public Builder setAccessTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        accessToken_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private int platformType_ = 0;
      /**
       * <code>.com.github.im.common.connect.model.proto.PlatformType platformType = 5;</code>
       * @return The enum numeric value on the wire for platformType.
       */
      @java.lang.Override public int getPlatformTypeValue() {
        return platformType_;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.PlatformType platformType = 5;</code>
       * @param value The enum numeric value on the wire for platformType to set.
       * @return This builder for chaining.
       */
      public Builder setPlatformTypeValue(int value) {
        platformType_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.PlatformType platformType = 5;</code>
       * @return The platformType.
       */
      @java.lang.Override
      public com.github.im.common.connect.model.proto.User.PlatformType getPlatformType() {
        com.github.im.common.connect.model.proto.User.PlatformType result = com.github.im.common.connect.model.proto.User.PlatformType.forNumber(platformType_);
        return result == null ? com.github.im.common.connect.model.proto.User.PlatformType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.PlatformType platformType = 5;</code>
       * @param value The platformType to set.
       * @return This builder for chaining.
       */
      public Builder setPlatformType(com.github.im.common.connect.model.proto.User.PlatformType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        platformType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.github.im.common.connect.model.proto.PlatformType platformType = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlatformType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        platformType_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.github.im.common.connect.model.proto.UserInfo)
    }

    // @@protoc_insertion_point(class_scope:com.github.im.common.connect.model.proto.UserInfo)
    private static final com.github.im.common.connect.model.proto.User.UserInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.im.common.connect.model.proto.User.UserInfo();
    }

    public static com.github.im.common.connect.model.proto.User.UserInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserInfo>
        PARSER = new com.google.protobuf.AbstractParser<UserInfo>() {
      @java.lang.Override
      public UserInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UserInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.im.common.connect.model.proto.User.UserInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_im_common_connect_model_proto_UserInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_github_im_common_connect_model_proto_UserInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023UserInfoProto.proto\022(com.github.im.com" +
      "mon.connect.model.proto\"\236\001\n\010UserInfo\022\020\n\010" +
      "username\030\001 \001(\t\022\016\n\006userId\030\002 \001(\003\022\r\n\005eMail\030" +
      "\003 \001(\t\022\023\n\013accessToken\030\004 \001(\t\022L\n\014platformTy" +
      "pe\030\005 \001(\01626.com.github.im.common.connect." +
      "model.proto.PlatformType*N\n\014PlatformType" +
      "\022\007\n\003WEB\020\000\022\013\n\007ANDROID\020\001\022\007\n\003IOS\020\002\022\013\n\007WINDO" +
      "WS\020\003\022\007\n\003MAC\020\004\022\t\n\005LINUX\020\005B0\n(com.github.i" +
      "m.common.connect.model.protoB\004Userb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_github_im_common_connect_model_proto_UserInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_im_common_connect_model_proto_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_github_im_common_connect_model_proto_UserInfo_descriptor,
        new java.lang.String[] { "Username", "UserId", "EMail", "AccessToken", "PlatformType", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
