name: Build KMP APK

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    uses: Assembles-J/.github/.github/workflows/android-build.yml@main
    with:
      java-version: '21'
      working-directory: Group-app/Group
      gradle-task: ':composeApp:assembleDebug'
      artifact-name: android-debug-apk
      artifact-path: Group-app/Group/composeApp/build/outputs/apk/debug/*.apk
